### ISSUE TITLE
Is there a way to use subfolders in my analysis?

### ISSUE THREAD

**Issue by VPetukhov** [workflowr/workflowr#95] opened 2018-01-23 21:38 UTC
Hi! In my `analysis` I have about 30 rmd files. It would be much more convenient to place them in separate folders. But if I do it, `wflow_build` doesn't see them. Is there a way to use subfloders within workflowr?

P.S. Thank you for your awesome package! If subfolders aren't possible right now, but there is a way to change the package, I'd really like to contribute.

**Comment by pcarbo** [comment] 2018-01-23 21:46
@VPetukhov Currently, `workflowr` only builds and commits Rmd files in `analysis` but not subdirectories. I agree it would be nice to organize R Markdown files into subdirectories, but I believe it is challenging to implement. @jdblischak can comment on whether he has plans to implement this at some point in the future.

**Comment by VPetukhov** [comment] 2018-01-23 21:48
@pcarbo ,
Thank you for the quick reply! Will be waiting for @jdblischak answer.

**Comment by jdblischak** [comment] 2018-01-23 22:28
@VPetukhov Thanks for using workflowr! Your feature request is a common one, and one I would like myself. Unfortunately at this point I do not plan on implementing it. This is because the workflowr package is built on top of the amazing [rmarkdown](http://rmarkdown.rstudio.com/) package (specifically the function `rmarkdown::render_site()`), and the rmarkdown package does not support having files in multiple subdirectories. From a development standpoint, I rely on the rmarkdown package handling the conversion of Rmd to html so that I can focus on the unique features added by workflowr (mainly integrating version control of the source Rmd files and the generated results files). From a user perspective, workflowr users can expect that anything that works with rmarkdown will work in workflowr. If the rmarkdown developers have been unable to find an elegant solution to this problem, I hesitate to take it on myself.

The reason this is so complicated is because the HTML files have to know the path to the various support files (e.g. figures, CSS/Javascript files), and the relative paths have to be generated from the location of where the R Markdown is located and then updated for where the final HTML is saved.

Since this is a common request, below I document where this has been discussed previously (this is mainly for my future self, so that I don't have to always hunt these down every time I re-consider this).

From the rmarkdown [source code for render_site](https://github.com/rstudio/rmarkdown/blob/42cd97bb36eacf23efe837a2fd946885586ee152/R/render_site.R#L161):

```
  # helper function to get all input files. includes all .Rmd and
  # .md files that don't start with "_" (note that we don't do this
  # recursively because rmarkdown in general handles applying common
  # options/elements across subdirectories poorly)
```

From https://github.com/rstudio/rmarkdown/issues/146#issuecomment-48591200:

> The current design assumes a single root directory for documents that want to share a lib_dir. It would be pretty involved to reverse this assumption

From https://github.com/rstudio/rmarkdown/issues/297#issuecomment-61723428:

> I really would like to have some subdirectory structure but that seems essentially impossible with the current implementation of `_output.yaml` (and how shared elements work)

From https://github.com/rstudio/rmarkdown/pull/653#issue-143035781:

>  render_site function which provides a standardized (and extensible) mechanism for generating websites from a collection of files within a directory

**Comment by VPetukhov** [comment] 2018-01-24 10:56
@jdblischak ,
Thank you for such detailed answer! I used small hack to deal with it, maybe it can be useful for other users who will read this thread.

Because the problem is in paths in html files, we can keep them all in the same folder. Their location doesn't really matter, because  html files can be organized with table of content in *index.html*. At the same time we want (and can) keep Rmd files organized by folders. To do it, we can use the following scheme:
1. All R Notebooks are stored in *"notebooks"* folder. All file path, which they use, can be either absolute or relative to their location (but not *"analysis"* folder).
2. Prior to site build, we create temporary Rmd files in "*analysis*" folder, which includes real Rmds as children. Furthermore, temporary files have the same yaml header as real ones. File names are generated by replacing all "/" characters in path with "__". For instance, if we have file *notebooks/folder/subfolder/test.Rmd* than new file will be *analysis/folder__subfloder__test.Rmd*.
3. These files are build with `wflow_build` and removed.

I wrapped `wflow_build` to `wflow_build_dir`, which implements the logic above:
```R
generate_rmd <- function(path, alias, dir) {
  path <- paste0(dir, '/', path)
  abs.path <- tools::file_path_as_absolute(paste0('../', path))
  cat(
    "---\n",
    yaml::as.yaml(rmarkdown::yaml_front_matter(abs.path)),
    "---\n\n",
    "**Source file\\:** ", path, "\n\n",
    "```{r child='", abs.path, "'}\n```",
    sep="",
    file=alias
  )
}

wflow_dir_build <- function(files=NULL, dir='notebooks', ...) {
  if (is.null(files)) {
    files <- list.files(paste0('../', dir), recursive=T, 
                        include.dirs=T, pattern="./*.(r|R)md")
  }
  else {
    for (file in files) {
      path <- paste0(dir, "/", file)
      if (!file.exists(paste0('../', path)))
        stop(paste0("File doesn't exist: ../", path))
    }
  }

  file_aliases <- gsub("/", "__", files)
  mapply(generate_rmd, files, file_aliases, dir=dir)
  workflowr::wflow_build(files=file_aliases, ...)
  invisible(file.remove(file_aliases))
}
```

Additionally, it places new line to the generated html, which shows path to the real Rmd file  
(e.g. **Source file:** notebooks/folder/subfolder/test.Rmd).

Example of generated file:
```
    ---
    title: "Test Rmd File"
    author: "Viktor Petukhov"
    date: 2018-01-24
    output: html_document
    ---

    **Source file\:** notebooks/folder/subfolder/test.Rmd

    ```{r child='/home/user/project/notebooks/folder/subfolder/test.Rmd'}
    ```
```

**Comment by pcarbo** [comment] 2018-01-24 13:43
@VPetukhov I'd like to propose a much simpler workaround using symbolic links, [which can be saved in a git repository](https://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links).

In the `dev` branch of [wflow-divvy](https://github.com/stephenslab/wflow-divvy), I have a new directory called `organized` with my R Markdown files organized into subfolders:

```
$ tree organized
organized
├── divvy-analyses
│   ├── first-glance.Rmd -> ../../analysis/first-glance.Rmd
│   ├── seasonal-trends.Rmd -> ../../analysis/seasonal-trends.Rmd
│   ├── station-map.Rmd -> ../../analysis/station-map.Rmd
│   └── time-of-day-trends.Rmd -> ../../analysis/time-of-day-trends.Rmd
└── setup
    ├── license.Rmd -> ../../analysis/license.Rmd
    └── setup.Rmd -> ../../analysis/setup.Rmd
```

Would this approach suit your needs?

**Comment by VPetukhov** [comment] 2018-01-27 20:20
Sorry for the delay with the answer, and thank you a lot for the attention to my question!

@pcarbo Thanks, it's a good idea. I considered the opposite case: create links from "*analysis*" to "*organized*", but it has several drawbacks I couldn't cope with. Yet, in case with organization of Rmd scripts with symlinks, you have to ensure their consistency by hands. Not a big deal, but it takes some time. And also, dealing with relative paths become a bit unobvious as you should keep in mind real location of a file. Though, it's really easy to organise and it doesn't require additional code, you're right.

@jdblischak 
> Do you have a GitHub repo that you could share so that I can test out how well your approach works?

I just created [it](https://github.com/VPetukhov/dropEstAnalysis) and didn't publish the data yet. So there is no way to rerun my scripts. Though I plan to fill the repo during the next week (I will write here when I complete). I really appreciate any comments you can give on it.

> Do you use wflow_publish() to publish the results?

I didn't grasp it all for now, so I prefer to commit everything by hands meanwhile. But I plan to include `wflow_publish` to my workflow in the nearest future.

> Have you experimented with blogdown?

No, should I? Actually, now I completely satisfied with your package. Does **blockdown** worth taking a look?

**Comment by jdblischak** [comment] 2018-01-29 20:11
> I just created it and didn't publish the data yet. So there is no way to rerun my scripts. Though I plan to fill the repo during the next week (I will write here when I complete). I really appreciate any comments you can give on it.

@VPetukhov Your site looks great! I like the nicely organized index page, the cool visualizations of single-cell data, and the [customized session-info chunk](https://github.com/VPetukhov/dropEstAnalysis/blob/9b0829b121503f67cad92f8f39422f9aa182ffcd/analysis/chunks.R#L35).

> I didn't grasp it all for now, so I prefer to commit everything by hands meanwhile. But I plan to include wflow_publish to my workflow in the nearest future.

Yes, please do read over the docs, e.g. try reading through `?wflow_publish`. I'd be grateful for any feedback on how to improve the documentation.

Briefly, `wflow_publish` performs a 3-step process of 1) committing the source Rmd files, then 2) building the HTML files, and finally 3) committing the generated HTML and figures. This cycle is critical to the reproducibility of a workflowr project. The commit version (i.e. SHA1) inserted at the top of each HTML file is meant to signify the exact state of the repository when the results were produced, which means the Rmd files need to have already been committed prior to building the HTML.

> No, should I? Actually, now I completely satisfied with your package. Does blockdown worth taking a look?

I mentioned blogdown because I am pretty sure it supports having a subdirectory structure. If that is a crucial feature for you, then it'd be worth taking a look. But of course I'm happy for you to continue using workflowr! :-)

**Comment by jdblischak** [comment] 2018-02-07 20:16
Adding another link from Yihui to keep all my research about this in one place:

https://github.com/rstudio/rmarkdown/issues/587#issuecomment-168437646

**Comment by jdblischak** [comment] 2018-05-05 15:25
Thanks for getting this conversation started, @VPetukhov. I'm closing this issue since I still think it will be too difficult to support subdirectories directly in workflowr (especially as I add other new features).

For future readers of this thread that would like to use subdirectories to organize the R Markdown files in their workflowr projects, here are two potential options:

* Use `wflow_build_dir` as proposed by @VPetukhov https://github.com/jdblischak/workflowr/issues/95#issuecomment-360094662
* Use symlinks as proposed by @pcarbo https://github.com/jdblischak/workflowr/issues/95#issuecomment-360138007

**Closed as completed by jdblischak** 2018-05-05 15:25 UTC
Labels: enhancement
