### ISSUE TITLE
Private workflowr site

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#66] opened 2017-09-01 04:34 UTC
Hi John,

I hope all is well.

We had some conversations a while ago about setting up private `workflowr` sites. Some of our data-generating collaborators are very concerned that potential competitors may discover the sites and try to scoop them, especially after they present interesting results in conferences. 

I have already received two requests to shut down two `workflowr` sites recently. (They even suggested that we should make the corresponding GitHub repos "private", which is easily doable.) 

Personally I am a big fan of open sciences, but it seems that setting up private sites may be an appealing feature for many data-sensitive projects.

Currently I have to manually turn on/off the sites by changing "GitHub Settings".

**Comment by pcarbo** [comment] 2017-09-01 12:30
@xiangzhu This is very timely---John & I were discussing this yesterday.

Please see Issue #59 for a related discussion.

Perhaps John & I can offer some additional recommendations here.

**Comment by jdblischak** [comment] 2017-09-01 14:42
@xiangzhu Thanks for reporting your experience with workflowr for collaborative projects. I also value open science, and a large motivation for creating workflowr was to encourage researchers to more openly share their work. However, I also appreciate that every project is different, and thus the complete openness supported by workflowr isn't compatible for every scientific study.

Here are the current options for using workflowr without a public website:

1. Have a private GitHub repo and don't host the website. Using workflowr in this scenario still provides the benefits of organizing the project, version controlling the development, and improving the reproducibility of the code. And if you have other collaborators actively working on the project, they can also view the website locally.

2. Have a private GitHub repo and host the website via the Beaker Browser. This allows collaborators to view the website online while still keeping it private, but it requires some additional installation for the recipients. This approach is currently described in PR https://github.com/jdblischak/workflowr/pull/65 to the FAQ vignette. If you have time, it would be great if you could read through this, try it out, and let us know your thoughts.

3. Self-host the website with secured access. This would require the workflowr user (or a collaborator) to have some systems administration skills and access to the resources for hosting the site.

Longer term I could imagine applying for some money to create a platform to host private workflowr sites. But that is not a top priority at the moment, especially because workflowr is trying to promote and facilitate open science (your particular projects involve data from human patients, but many studies do not involve such sensitive data).

**Comment by pcarbo** [comment] 2017-09-01 14:51
@xiangzhu By "view the website locally", this would involve downloading or cloning the repo and browsing the webpages that were downloaded using `file://...`.

There is also of course the option of sharing individual HTML files (and accompanying image files) via email, but you lose many of the benefits of the workflowr project site that way.

@jdblischak Maybe we should try ["Jekyll auth"](https://github.com/benbalter/jekyll-auth) (see also [this](http://www.alexandrejoseph.com/blog/2015-03-11-restricted-github-pages.html))?

**Comment by xiangzhu** [comment] 2017-09-01 17:53
@pcarbo @jdblischak  Thanks for the suggestions!

To address collaborators' pressing concerns, I will go with the first option (private repo + no website), which seems to be the easiest solution at this moment.

I will try the Beaker Browser approach soon. Thanks!

**Comment by jdblischak** [comment] 2017-09-01 22:10
> Maybe we should try "Jekyll auth" (see also this)?

@pcarbo I consider options such as these to fall under bullet point 3 above. There are so many different ways to host a website. The current default is to offer instructions for GitHub Pages because this only requires a GitHub account and one click. The options you linked to involve at least one user to get a Heroku account and create a GitHub organization, then all collaborators that want to view the site have to register for a GitHub account and join the organization.

For now my approach is to wait for community support, similar to how we are adding the documentation for Beaker Browser. If a motivated workflowr user wants to troubleshoot hosting on Heroku and submit some documentation, I would be happy to merge it.

**Comment by jdblischak** [comment] 2017-09-01 22:10
> I will try the Beaker Browser approach soon. Thanks!

@xiangzhu Great. Please try it out and send us your feedback. Thanks!

**Comment by pcarbo** [comment] 2017-09-02 00:15
@jdblischak Sounds good.

**Comment by xiangzhu** [comment] 2017-11-06 21:56
@jdblischak @pcarbo

Hi John and Peter,

Hope all is well!

Due to two new projects containing highly sensitive materials, I am revisiting the documents about setting up Beaker Browser: https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-05-faq.Rmd#can-i-share-workflowr-websites-directly-with-collaborators-in-a-secure-fashion

If I understand it correctly, in order to view the Beaker Browser version of workflowr site, the viewers also have to install and run Beaker Browser, right?

If this is the case, then I think Beaker Browser may be even less convenient than directly sending html/pdf files via emails. Some of my target viewers may be too busy to reply emails sometimes, let alone installing and running software!

I wonder if there is any update regarding "private workflowr" site, other than the Beaker Browser.

**Comment by pcarbo** [comment] 2017-11-06 22:18
@xiangzhu Yes, there are several technical barriers to Beaker Browser that make it less appropriate for sharing results with less technically inclined PIs.

**Comment by jdblischak** [comment] 2017-11-07 04:08
> If I understand it correctly, in order to view the Beaker Browser version of workflowr site, the viewers also have to install and run Beaker Browser, right?

@xiangzhu Correct, the Beaker Browser needs to be installed, and thus is less ideal for sharing with collaborators that just want to quickly view the results.

The content in `docs/` is a static website. Thus any solution you can find to serve a password-protected website can work with the `docs/` content. I don't have the web hosting expertise to to develop a standard solution, and I am also weary of advertising any solution as truly secure. Any solution will need to treat the static website as if it is a dynamic website. As examples, here is a [tutorial on a standard approach to password protecting content on a web server with Apache](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-14-04), and here is a [tutorial on serving a static website as a Ruby app on Heroku](http://daverupert.com/2015/02/jekyll-heroku-dropbox/).

**Comment by pcarbo** [comment] 2018-01-15 19:31
@jdblischak @xiangzhu See [here](https://github.com/stephenslab/ipynb-website/issues/5) for an approach that Gao & I are currently exploring. I think it could be incorporated into workflowr using the header and/or footer, if one was motivated to do so.

**Comment by xiangzhu** [comment] 2018-01-15 20:39
@pcarbo Hi Peter -- Thanks for the update!

I would like to try it out if this feature is implemented in the dev version. I have multiple projects during my postdoc training that cannot fully communicated via public `workflowr`  sites.

**Comment by pcarbo** [comment] 2018-01-19 18:05
@xiangzhu @jdblischak Thinking about this further, I don't think the solution given above is any safer than generating a random SHA1 and hiding the webpages within a subdirectory of that name. See [here](https://pcarbo.github.io/pcarbo/989d7bf4b2bc3ecd0fea06b68b363444db2e5e78/index.html) for an example of a web address that is "protected." (Although obviously not protected anymore since I just made the link public!) You would then share this address to your collaborators; it would be extremely difficult (not impossible) for anyone who did not have this address to discover the protected webpage. Sharing a password instead of the actual URL does not provide any additional protection.

There isn't an elegant way to implement this solution within the `workflowr` package right now, but for now I would propose editing `_site.yml` to, for example, `output_dir: "../docs/989d7bf4b2bc3ecd0fea06b68b363444db2e5e78"`, and moving the HTML files accordingly. I did a small amount of testing and it seems to work with the current implementation. The most annoying part is that you will have to work with these long folder names.

Note the random URL was generated using [this code snippet provided by Gao](https://github.com/stephenslab/ipynb-website/issues/5#issuecomment-357784528).

**Comment by jdblischak** [comment] 2018-01-20 21:27
Thanks for investigating this, Peter. From my previous research, my understanding is that it is impossible to make a static website truly password-protected. Any Javascript tricks implementing passwords can give the impression of security, but are easily bypassed by anyone that is motivated. Adding some extra security measures may be sufficient for users that just want privacy for the sake of privacy. However, some users want privacy because their data is truly sensitive. I don't want to give the impression that any potential solution we implement is sufficiently secure for sensitive data.

In my experience, new workflowr sites are essentially undiscoverable even when making very specific search queries. Do we have evidence that adding a SHA1 to the URL makes them any more hidden? I admit that I don't understand search engines well enough to evaluate this. My understanding is that pages are indexed by inbound and outbound links, and thus the length of the page's URL would be irrelevant.

**Comment by pcarbo** [comment] 2018-01-21 01:16
> Any Javascript tricks implementing passwords can give the impression of security, but are easily bypassed by anyone that is motivated. 

@jdblischak That is also my impression.

> My understanding is that pages are indexed by inbound and outbound links, and thus the length of the page's URL would be irrelevant.

@jdblischak It should be hidden as long as there is no inbound link. Yes in principle the page's URL is irrelevant, but a presumably `index.html` is a lot easier to discover or accidentally stumble upon than `cp3w4.html`. There is no fundamental reason for using `SHA1` other than convenience.

**Comment by jdblischak** [comment] 2018-05-04 03:09
I'm closing this since there is not much I can do. workflowr only creates a static website, and most free hosting services only provide static web hosting. The only way to truly secure a workflowr website would be to host it using a web server (e.g. Apache), but that would be much more involved than activating GitHub Pages.

**Closed as completed by jdblischak** 2018-05-04 03:09 UTC

**Comment by vorpalvorpal** [comment] 2022-02-22 23:26
I realise that you have closed this issue, but I'm just wondering if you would consider using [staticrypt](https://github.com/robinmoisson/staticrypt) as a option. This takes a static html page, transforms it using AES-256 to a whole lot of gobblety gook, and then puts a little AJAX widget on top that prompts the user for a password which is then used to re-transform the page in the browser. So this doesn't rely on hiding the page (as per the previous suggestions), but actually publishing an encoded version of the page.

This isn't perfect since there is no real way of protecting against brute-force attacks (and so wouldn't be appropriate for genuinely secret stuff), but is more than sufficient for just keeping things private.

Just as background, my use case is data analysis for a local council. While it would be nice to have everything open and available to the public, there are requirements that anything that is made public is checked and approved by appropriate levels of management. When things are at the stage of just being shared internally, it would be nice to have the ease of workflowr and github pages but still some basic level of privacy.

**Comment by jdblischak** [comment] 2022-03-29 14:47
> you would consider using [staticrypt](https://github.com/robinmoisson/staticrypt) as a option.

@vorpalvorpal Thanks for sharing this cool resource! I agree this is nice to get a decent level of privacy when hosting via GitHub Pages. The static site generated by workflowr is defininitely compatible with staticrypt. However, you would need to run staticrypt yourself. Decrypting requires installing and running this Javascript command-line tool. Having to install Node (cross-platform) and shell out to execute it would require a lot of extra engineering to do from within an R package. However, for your use case, you could install Node and staticrypt on your machine and create a little shell script that encrypts all the files in `docs`. You would then run it each time after running `wflow_publish()`. The links to past versions of the HTML file might get wonky doing this, so you'd want to do an experiment first.

I have a vignette, [Alternative strategies for deploying workflowr websites](https://workflowr.github.io/workflowr/articles/wflow-08-deploy.html), for sharing user-provided documentation for alternative deployment strategies. I'd love to have an entry on how to use staticrypt. Please let me know if you're interested in contributing and if you have any questions.

Another important thing to mention is that [GitLab provides website access control for free](https://workflowr.github.io/workflowr/articles/wflow-06-gitlab.html#access-control-for-private-sites). You could either use GitLab in place of GitHub, or use a hybrid (develop your code collaboratively on GitHub, and then occasionally copy to GitLab to deploy securely).

> my use case is data analysis for a local council

I have to say this is really awesome! I love to see workflowr being useful for many different domains, especially for something as important as local governmental decision-making.
