### ISSUE TITLE
Possibly redundant bullet points in the reproducibility report

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#129] opened 2018-10-17 23:21 UTC
Hi John @jdblischak  -- This may be a silly and minor inquiry. I just realize that there are two bullet points for certain items in the reproducibility report; below is an example. 

<img width="481" alt="screen shot 2018-10-17 at 4 06 40 pm" src="https://user-images.githubusercontent.com/5986023/47121478-a8a8ea80-d227-11e8-8b13-6129355e688d.png">

I feel that the round dots (circled in the example above) may be redundant (since we also have triangles there)? If so, to comply with the simplistic style of `workflowr`, perhaps these round dots should be removed?

I get these round dots in the following version:

```r
> packageVersion("workflowr")
[1] ‘1.1.1’
```

**Comment by jdblischak** [comment] 2018-10-18 12:39
@xiangzhu I agree the redundancy is annoying. Unfortunately the triangles do not show up in Firefox (at least for me and Peter). Thus the bullet points provide useful formatting in this instance.

Here's a screenshot of the reproducibility report in my Firefox browser:

<img width="728" alt="screen shot 2018-10-18 at 8 37 19 am" src="https://user-images.githubusercontent.com/1608317/47154718-0fbeb180-d2b1-11e8-9f09-a98617697640.png">

I've been experimenting with different layouts to improve the reproducibility report. I'd like it to use less vertical space while also being informative. In other words, this redundancy will be eliminated in a future release.

**Comment by xiangzhu** [comment] 2018-10-18 17:04
Thanks! I didn't know the triangles do not show up in Firefox. In this case, it certainly makes sense to have those round dots.

> I'd like it to use less vertical space while also being informative.

To save space, I wonder if it is possible to make this entire section **foldable**, like you did for "Expand here to see past versions:".

As a user I rarely read this section unless something goes wrong -- similar to the Session Info section; see Issue #120.

**Comment by jdblischak** [comment] 2018-10-19 14:31
I'll go ahead and close it since I am already working on it. Thanks for the ideas and discussion!

**Closed as completed by jdblischak** 2018-10-19 14:31 UTC
