### ISSUE TITLE
error from wflow_use_github

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#186] opened 2020-01-11 17:41 UTC
I got the following error when using `wflow_use_github("stephenslab")`

```
> wflow_use_github("stephenslab")
Summary from wflow_use_github():
username: stephenslab
respository: reading_lists
* The website directory is already named docs/
* Output directory is already set to docs/
* Set remote "origin" to https://github.com/stephenslab/reading_lists.git
* Added GitHub link to navigation bar
* Committed the changes to Git

To proceed, you have two options:

1. Have workflowr attempt to automatically create the repository "reading_lists" on
GitHub. This requires logging into GitHub and enabling the workflowr-oauth-app access to
the account "stephenslab".

2. Create the repository "reading_lists" yourself by going to https://github.com/new and
entering "reading_lists" for the Repository name. This is the default option.

Enter your choice (1 or 2): 1
You chose option 1: have workflowr attempt to create repo
Requesting authorization for workflowr app to access GitHub account stephenslab
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Creating repository reading_lists
Error in utils::browseURL(repo_url) : 
  'url' must be a non-empty character string
In addition: Warning message:
In create_gh_repo(username, repository) :
  Failed to create repository reading_lists. Reason: Not Found
```

Here is my session info:
```> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.6.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3      rstudioapi_0.10 knitr_1.26      magrittr_1.5    R6_2.4.1        rlang_0.4.2    
 [7] stringr_1.4.0   httr_1.4.1      tools_3.6.0     xfun_0.11       git2r_0.26.1    htmltools_0.4.0
[13] yaml_2.2.0      digest_0.6.23   rprojroot_1.3-2 processx_3.4.1  callr_3.4.0     later_1.0.0    
[19] promises_1.1.0  fs_1.3.1        ps_1.3.0        curl_4.3        glue_1.3.1      evaluate_0.14  
[25] rmarkdown_1.18  stringi_1.4.3   compiler_3.6.0  backports_1.1.5 jsonlite_1.6    httpuv_1.5.2 
```

**Comment by pcarbo** [comment] 2020-01-11 20:40
@stephens999 I see the repository exists: https://github.com/stephenslab/reading_lists

Did you create it yourself after this command failed? Or did this command succeed in creating the repository, and the errors are misleading?

**Comment by stephens999** [comment] 2020-01-12 00:05
i created myself

**Comment by jdblischak** [comment] 2020-01-12 19:46
I can confirm the error. The problem arises from trying to authenticate with a GitHub organization account instead of a personal account.

When I ran the code below, each time it created the new GitHub repository in my personal account even though the second time I requested it be created in the organization account [workflowr](https://github.com/workflowr):

```
rmd <- tempfile(fileext = ".Rmd")
file.create(rmd)
wflow_quickstart(rmd, "jdblischak", change_wd = FALSE)

rmd <- tempfile(fileext = ".Rmd")
file.create(rmd)
wflow_quickstart(rmd, "workflowr", change_wd = FALSE)
```

@stephens999 The same thing happened to you. You wanted to create `stephenslab/reading_lists`, but instead it created [`stephens999/reading_lists`](https://github.com/stephens999/reading_lists).

I mistakenly assumed that the GitHub API would be able to handle authenticating access to an organization account when a user logs into their personal account. I'll investigate to see if this is possible.

**Comment by pcarbo** [comment] 2020-01-12 20:00
Good discovery!

**Comment by jdblischak** [comment] 2020-01-13 01:51
The API endpoint to [create a repository](https://developer.github.com/v3/repos/#create) for an organization is different than creating a repository for a user.

* User: `POST /user/repos`
* Organization: `POST /orgs/:org/repos`

Thus we need someway for the workflowr user to indicate if the account they provide is a user or organization account. To throw out some potential ideas:

* Add a character argument `organization` that would override `username`. Thus for Matthew's use case above, he would have run `wflow_use_github(organization = "stephenslab")`.
* Add a flag argument `organization` that is `FALSE` by default. But if `TRUE`, will use the API endpoint for organizations. Thus for this use  case the function call would have been `wflow_use_github("stephenslab", organization = TRUE)`.

Thoughts on these potential implementations? Alternative ideas?

**Comment by stephens999** [comment] 2020-01-13 01:55
Personally I prefer the first as it seems to correspond more to GitHub
terminology. It is not like an organization is a special case of a user,
but rather a separate notion.

**Comment by pcarbo** [comment] 2020-01-13 03:17
I also prefer the first approach.

**Comment by jdblischak** [comment] 2020-01-14 22:00
In 31f9c980bdce053d39cdce151fef0d6244020ef1 I've added the argument `organization` to `wflow_use_github()` and `wflow_quickstart()` to support creating repositories for GitHub organizations. Please test it out on the branch "organization".

```
setwd(tempdir())
library(workflowr)
rmd <- tempfile(fileext = ".Rmd")
file.create(rmd)
wflow_quickstart(rmd, organization = "stephenslab", change_wd = FALSE)
```

The analogous concept for GitLab is a [Group](https://gitlab.com/help/user/group/index). With any luck, it will be possible to create the repository during the initial `git push` just like for a user account. If that's the case, then GitLab support will only require documentation updates.

**Comment by stephens999** [comment] 2020-01-15 15:17
I did devtools::install_github("jdblischak/workflowr", ref="31f9c98")
is that the right way to install?

I got an error:
Error in wflow_quickstart(rmd, organization = "stephenslab", change_wd =
FALSE) :
  unused argument (organization = "stephenslab")

**Comment by jdblischak** [comment] 2020-01-15 16:29
> I did devtools::install_github("jdblischak/workflowr", ref="31f9c98")
is that the right way to install?

@stephens999 That works, though I recommend using the branch name, i.e. `ref="organization"`, since this is easier to type and also will include any more recent commits.

I ran your command to install workflowr, and then confirmed that I could use the argument `organization`. So I'm not sure what caused your error. Do you get that error every time?

@pcarbo Could you please test to see if it works on your machine?

**Comment by pcarbo** [comment] 2020-01-15 18:29
I'm looking at this now.

@stephens999 I'm guessing you forgot to reload the package after installing it. The safest thing to do is to restart R after installing the package.

**Comment by pcarbo** [comment] 2020-01-15 18:43
@jdblischak @stephens999 Worked for me! See [here](https://github.com/stephenslab/test). Note I installed from commit `d1fb26f`.

```
> library(workflowr)
wflow_quickstart("test.Rmd",organization = "stephenslab")
This is workflowr version 1.6.0.9000
Run ?workflowr for help getting started
> wflow_quickstart("test.Rmd",organization = "stephenslab")
wflow_quickstart:
* Started the project with wflow_start() in /Users/pcarbo/Desktop/test/
* Changed working directory to /Users/pcarbo/Desktop/test/
* Copied test.Rmd to /Users/pcarbo/Desktop/test/analysis/
* Configured local Git repo to host project on GitHub.com
* Building files
* Published the analysis files with wflow_publish()
To proceed, you have two options:
1. Have workflowr attempt to automatically create the repository "test"
on GitHub. This requires logging into GitHub and enabling the
workflowr-oauth-app access to the account "stephenslab".
2. Create the repository "test" yourself by going to
https://github.com/new and entering "test" for the Repository name.
This is the default option.
Enter your choice (1 or 2): 1
You chose option 1: have workflowr attempt to create repo
* To do: Run wflow_git_push() to push your project to github
> wflow_git_push()
Please enter your username: pcarbo
Please enter your password: ********************
Summary from wflow_git_push
Pushing to the branch "master" of the remote repository "origin"
Using the HTTPS protocol
The following Git command was run:
  $ git push origin master
```

**Comment by pcarbo** [comment] 2020-01-15 18:44
@jdblischak One comment. For the prompt, it could easily happen that someone (like me) accidentally hits enter in the prompt, or mistypes. Would it be possible to repeat the `Enter your choice (1 or 2)` if the selection is invalid?

**Comment by stephens999** [comment] 2020-01-15 18:47
Ok it works for me after restarting R.
Matthew

**Comment by jdblischak** [comment] 2020-01-15 21:18
@stephens999 @pcarbo Thanks for testing!

I created a [GitLab Group named "workflowr"](https://gitlab.com/workflowr) and confirmed that `wflow_quickstart()`/`wflow_use_gitlab()` work fine as is. In other words, `wflow_git_push()` automatically creates the repository during the first push. So I just need to make sure the documentation is clear that the argument `username` can be a personal GitHub account, a personal GitLab account, or a group GitLab account.

> Would it be possible to repeat the Enter your choice (1 or 2) if the selection is invalid?

@pcarbo I'll test it out using a `while` loop.

**Comment by jdblischak** [comment] 2020-01-16 14:31
@pcarbo I implemented the `while` loop in cf5feaf1da00ef76776b4e9cf01c53065f00c457 on the branch "organization". Please test it out and let me know if it works as you expect.

**Comment by pcarbo** [comment] 2020-01-16 16:35
Much better. Here's an example:

```
To proceed, you have two options:
1. Have workflowr attempt to automatically create the repository
"test2" on GitHub. This requires logging into GitHub and enabling the
workflowr-oauth-app access to the account "stephenslab".
2. Create the repository "test2" yourself by going to
https://github.com/new and entering "test2" for the Repository name.
This is the default option.
Enter your choice (1 or 2):
Invalid input.
Enter your choice (1 or 2): 3
Invalid input.
Enter your choice (1 or 2): 2
You chose option 2: create the repo yourself
* To do: Create test2 on GitHub.com
* To do: Run wflow_git_push() to push your project to github
```

**Comment by jdblischak** [comment] 2020-01-16 22:20
@pcarbo Great. In 2944c032ce327882bda3e21043819a333e1a2b81, I went ahead and applied similar functionality to the other places where workflowr prompts the user for input via `readline()`.

**Comment by jdblischak** [comment] 2020-01-17 14:50
The features discussed in this Issue have been merged into master.

**Closed as completed** 2020-01-17 14:49 UTC
