### ISSUE TITLE
Error: rmd must exist

### ISSUE THREAD

**Issue by JohnReid** [workflowr/workflowr#54] opened 2017-07-14 07:50 UTC
Often after using workflowr for a while I start to get the error below. Restarting my R session always fixes this.

```
> wflow_build('Petropoulos-2016-diffusion-map.Rmd')
Building Petropoulos-2016-diffusion-map.Rmd
Build failed. See log files for full details.
stdout: /tmp/workflowr/Petropoulos-2016-diffusion-map.Rmd-2017-07-14-08h-45m-16s-out.txt
stderr: /tmp/workflowr/Petropoulos-2016-diffusion-map.Rmd-2017-07-14-08h-45m-16s-err.txt
NA
Error: rmd must exist
> traceback()
7: stop(e$message, call. = FALSE)
6: value[[3L]](cond)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
3: tryCatch(callr::r_safe(build_rmd, args = list(rmd, seed), stdout = stdout_file,
       stderr = stderr_file), error = function(e) {
    ...
2: build_rmd_external(f, seed = seed, log_dir = log_dir)
1: wflow_build("Petropoulos-2016-diffusion-map.Rmd")
```

The error log looks like:
```
Error in (function (rmd, seed, ...)  : rmd must exist
Calls: withCallingHandlers -> saveRDS -> do.call -> <Anonymous> -> <Anonymous>
Execution halted
```

I should say I'm running workflowr on separate projects in two copies of R concurrently. Could this be confusing workflowr?

**Comment by pcarbo** [comment] 2017-07-14 11:54
Thanks @JohnReid for sharing.

> I should say I'm running workflowr on separate projects in two copies of R concurrently. 

@jdblischak Have you tested `workflowr` in this situation before? I have not.

**Comment by jdblischak** [comment] 2017-07-14 13:07
> I should say I'm running workflowr on separate projects in two copies of R concurrently. Could this be confusing workflowr?

@JohnReid Could you please describe your directory layout for the two separate projects? workflowr uses the package `rprojroot` to find the root of the workflowr directory by identifying the location of the `.Rproj` file. My initial guess is that workflowr is finding the `.Rproj` file for the wrong project.

**Comment by JohnReid** [comment] 2017-07-14 20:15
Well the layout is in two separate directory structures, each with a `.Rproj` file in the root. Like I say the problem is intermittent and I'm not sure what changes to cause it. If I have any more ideas or clues, I'll post them there.

**Comment by jdblischak** [comment] 2017-07-14 20:39
> Well the layout is in two separate directory structures, each with a .Rproj file in the root.

OK. If the projects are separated and you don't use `setwd()` to switch between them, then this shouldn't happen. I've labeled this a bug and will experiment to see if I can reproduce it.

> Like I say the problem is intermittent and I'm not sure what changes to cause it. If I have any more ideas or clues, I'll post them there.

Yes, please do post any clues you may discover to this Issue. To help me reproduce this, could you please send me the output of `sessionInfo()` so that I can see which version of R you are using on which operating system? Also, if your workflowr website is live for either or both of the projects in question, please post link(s) to this Issue.

**Comment by JohnReid** [comment] 2017-07-14 20:42
I'm afraid neither website is live. Here is the session info:
```
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu
 ui       X11
 language en_GB:en
 collate  en_GB.UTF-8
 tz       GB
 date     2017-07-14

Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version  date       source
 assertthat     0.2.0    2017-04-11 CRAN (R 3.3.3)
 backports      1.1.0    2017-05-22 CRAN (R 3.4.0)
 base         * 3.4.1    2017-07-08 local
 bindr          0.1      2016-11-13 CRAN (R 3.4.1)
 bindrcpp     * 0.2      2017-06-17 CRAN (R 3.4.0)
 bitops         1.0-6    2013-08-17 CRAN (R 3.2.2)
 broom          0.4.2    2017-02-13 CRAN (R 3.2.5)
 caTools        1.17.1   2014-09-10 CRAN (R 3.2.2)
 class          7.3-14   2015-08-30 CRAN (R 3.4.0)
 cluster        2.0.6    2017-03-16 CRAN (R 3.4.0)
 coda           0.19-1   2016-12-08 CRAN (R 3.4.0)
 codetools      0.2-15   2016-10-05 CRAN (R 3.3.1)
 colorout     * 1.1-1    2015-12-02 local
 colorspace     1.3-2    2016-12-14 CRAN (R 3.2.5)
 commonmark     1.2      2017-03-01 CRAN (R 3.4.0)
 compiler       3.4.1    2017-07-08 local
 crayon         1.3.2    2016-06-28 CRAN (R 3.2.5)
 datasets     * 3.4.1    2017-07-08 local
 DeLorean     * 1.2.4    <NA>       local
 dendextend     1.5.2    2017-03-28 CRAN (R 3.3.3)
 DEoptimR       1.0-8    2016-11-19 CRAN (R 3.3.3)
 devtools     * 1.13.2   2017-06-02 CRAN (R 3.4.0)
 digest         0.6.12   2017-01-27 CRAN (R 3.2.5)
 diptest        0.75-7   2015-06-08 CRAN (R 3.2.5)
 dplyr        * 0.7.0    2017-06-09 CRAN (R 3.4.0)
 evaluate       0.10     2016-10-11 CRAN (R 3.2.5)
 fastICA        1.2-1    2017-06-12 CRAN (R 3.4.0)
 flexmix        2.3-14   2017-04-28 CRAN (R 3.4.0)
 foreach        1.4.3    2015-10-13 CRAN (R 3.2.3)
 foreign        0.8-68   2017-04-24 CRAN (R 3.4.0)
 fpc            2.1-10   2015-08-14 CRAN (R 3.2.5)
 functional     0.6      2014-07-16 CRAN (R 3.2.2)
 gclus          1.3.1    2012-06-25 CRAN (R 3.2.3)
 gdata          2.18.0   2017-06-06 CRAN (R 3.4.0)
 ggplot2      * 2.2.1    2016-12-30 CRAN (R 3.2.5)
 ggthemes     * 3.4.0    2017-02-19 CRAN (R 3.4.0)
 git2r          0.18.0   2017-01-01 CRAN (R 3.4.0)
 glue           1.1.0    2017-06-13 CRAN (R 3.4.0)
 gplots         3.0.1    2016-03-30 CRAN (R 3.2.4)
 graphics     * 3.4.1    2017-07-08 local
 grDevices    * 3.4.1    2017-07-08 local
 grid           3.4.1    2017-07-08 local
 gridExtra      2.2.1    2016-02-29 CRAN (R 3.2.5)
 gtable         0.2.0    2016-02-26 CRAN (R 3.2.4)
 gtools         3.5.0    2015-05-29 CRAN (R 3.2.2)
 highr          0.6      2016-05-09 CRAN (R 3.2.5)
 htmltools      0.3.6    2017-04-28 CRAN (R 3.4.0)
 inline         0.3.14   2015-04-13 CRAN (R 3.2.2)
 iterators      1.0.8    2015-10-13 CRAN (R 3.2.3)
 kernlab        0.9-25   2016-10-03 CRAN (R 3.2.5)
 KernSmooth     2.23-15  2015-06-29 CRAN (R 3.4.0)
 knitr          1.16     2017-05-18 CRAN (R 3.4.0)
 labeling       0.3      2014-08-23 CRAN (R 3.2.2)
 lattice        0.20-35  2017-03-25 CRAN (R 3.3.3)
 lazyeval       0.2.0    2016-06-12 CRAN (R 3.2.5)
 magrittr       1.5      2014-11-22 CRAN (R 3.2.2)
 MASS           7.3-47   2017-04-21 CRAN (R 3.4.0)
 mclust         5.3      2017-05-21 CRAN (R 3.4.0)
 memoise        1.1.0    2017-04-21 CRAN (R 3.4.0)
 methods      * 3.4.1    2017-07-08 local
 mnormt         1.5-5    2016-10-15 CRAN (R 3.2.5)
 modeltools     0.2-21   2013-09-02 CRAN (R 3.2.5)
 munsell        0.4.3    2016-02-13 CRAN (R 3.2.4)
 mvtnorm        1.0-6    2017-03-02 CRAN (R 3.2.5)
 nlme           3.1-131  2017-02-06 CRAN (R 3.4.0)
 nnet           7.3-12   2016-02-02 CRAN (R 3.4.0)
 nvimcom      * 0.9-33   2017-07-11 local
 parallel       3.4.1    2017-07-08 local
 pkgconfig      2.0.1    2017-03-21 CRAN (R 3.4.0)
 plyr           1.8.4    2016-06-08 CRAN (R 3.2.5)
 prabclus       2.2-6    2015-01-14 CRAN (R 3.2.5)
 psych          1.7.5    2017-05-03 CRAN (R 3.4.0)
 R6             2.2.2    2017-06-17 CRAN (R 3.4.0)
 RColorBrewer * 1.1-2    2014-12-07 CRAN (R 3.2.4)
 Rcpp         * 0.12.11  2017-05-22 CRAN (R 3.4.0)
 registry       0.3      2015-07-08 CRAN (R 3.2.3)
 reshape2     * 1.4.2    2016-10-22 CRAN (R 3.2.5)
 rlang          0.1.1    2017-05-18 CRAN (R 3.4.0)
 rmarkdown      1.6      2017-06-15 CRAN (R 3.4.0)
 robustbase     0.92-7   2016-12-09 CRAN (R 3.3.3)
 roxygen2       6.0.1    2017-02-06 CRAN (R 3.4.0)
 rprojroot      1.2      2017-01-16 CRAN (R 3.2.5)
 rstan          2.15.1   2017-04-19 CRAN (R 3.4.0)
 scales         0.4.1    2016-11-09 CRAN (R 3.2.5)
 seriation      1.2-2    2017-05-09 CRAN (R 3.4.0)
 setwidth     * 1.0-4    2015-07-07 CRAN (R 3.2.2)
 StanHeaders    2.15.0-1 2017-04-19 CRAN (R 3.4.0)
 stats        * 3.4.1    2017-07-08 local
 stats4         3.4.1    2017-07-08 local
 stringi        1.1.5    2017-04-07 CRAN (R 3.3.3)
 stringr      * 1.2.0    2017-02-18 CRAN (R 3.2.5)
 testthat       1.0.2    2016-04-23 CRAN (R 3.2.5)
 tibble         1.3.3    2017-05-28 CRAN (R 3.4.0)
 tidyr          0.6.3    2017-05-15 CRAN (R 3.4.0)
 tools          3.4.1    2017-07-08 local
 trimcluster    0.1-2    2012-10-29 CRAN (R 3.2.5)
 TSP            1.1-5    2017-02-22 CRAN (R 3.4.0)
 utils        * 3.4.1    2017-07-08 local
 viridis        0.4.0    2017-03-27 CRAN (R 3.3.3)
 viridisLite    0.2.0    2017-03-24 CRAN (R 3.3.3)
 whisker        0.3-2    2013-04-28 CRAN (R 3.2.2)
 withr          1.0.2    2016-06-20 CRAN (R 3.4.0)
 xml2           1.1.1    2017-01-24 CRAN (R 3.3.3)
 yaml           2.1.14   2016-11-12 CRAN (R 3.2.5)
```

**Comment by jdblischak** [comment] 2017-07-14 20:49
> I'm afraid neither website is live.

No hurry!

> Here is the session info:

Thanks. Your setup appears very similar to mine, so hopefully that will help me reproduce the bug.

**Comment by jdblischak** [comment] 2018-05-05 15:31
@JohnReid I'm going to close this Issue since I was never able to reproduce it. Please do re-open it and update me if this happens again. After the error happens, please run `getwd()` and `file.exists("filename.Rmd")` to see if it is an filepath issue.

In my experience, when I have multiple RStudio projects open at once, I occasionally have the issue where the current working directory is changed after restarting the R session (e.g. it will change to my home directory or to the other project). Maybe that behavior could be contributing here.

**Closed as completed by jdblischak** 2018-05-05 15:31 UTC
Labels: bug
