### ISSUE TITLE
Build analysis/*.Rmd in specific order

### ISSUE THREAD

**Issue by antass** [workflowr/workflowr#164] opened 2019-05-08 14:21 UTC
1. Describe the suggested feature.
It would be nice to be able to specify the order in which the `analysis/*.Rmd` files are build with `wflow_build()`. Maybe some sort of a dependency requirement added to the front matter in each `.Rmd`?

2. Describe why you think this feature is needed.
Sometimes an output from one `.Rmd` becomes an input into another. I follow the `Import > Tidy > Transform > Model > Visualize` schema and if I update my `transform.Rmd`, the new output won't be fed into `model.Rmd`, because `model.Rmd` gets built first since the files are built in alphabetical order. Adding double digit prefixes to the files is a working solution, but it would be nice to define the dependencies more "organically". This would be particularly helpful when adding a step in the middle of the workflow - renaming all the downstream files wouldn't be necessary.

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.
```
> packageVersion("workflowr")
[1] ‘1.3.0’
```

**Comment by pcarbo** [comment] 2019-05-08 14:53
@jdblischak If I run `wflow_build(c("analysis1.Rmd", "analysis2.Rmd"))`, do the files always get build in the order in which they are listed? If so, we should make that clear in the description of the `file` argument.

**Comment by jdblischak** [comment] 2019-05-08 14:59
> It would be nice to be able to specify the order in which the analysis/*.Rmd files are build with wflow_build(). Maybe some sort of a dependency requirement added to the front matter in each .Rmd?

@antass Agreed! That is definitely I feature we want to add. It will add a lot of complexity to workflowr, so I want to make sure to get it right. See #9 for our past discussion on this.

> Adding double digit prefixes to the files is a working solution

Unfortunately that is the best current solution.

@antass A few questions for you on a potential implementation. 

Let's say that part of the pipeline is the following steps:

*  `analysis/tidy.Rmd`
    * input: `data/raw.csv`
    * output: `output/tidy.csv`
*  `analysis/transform.Rmd`
    * input: `output/tidy.csv`
    * output: `output/transformed.csv`

Then the YAML header of `analysis/tidy.Rmd` would contain:

```
---
output: workflowr::wflow_html
wflow_pipeline:
  input:
    - data/raw.csv
  output:
    - output/tidy.csv
---
```

And the YAML header of `analysis/transform.Rmd` would contain:

```
---
output: workflowr::wflow_html
wflow_pipeline:
  input:
    - output/tidy.csv
  output:
    - output/transformed.csv
---
```

Then running `wflow_build("analysis/transform.Rmd")` would first build `analysis/tidy.Rmd` if any changes had been made to it.

The more complicated case is `wflow_publish("analysis/transform.Rmd")` since it also has to handle all the version control with Git. In this case it would perform the following steps (assuming `tidy.Rmd` has been edited):

1. Commit changes to `data/raw.csv` and `analysis/tidy.Rmd`
1. Build `analysis/tidy.Rmd`
1. Commit  `docs/tidy.html` and `output/tidy.csv`
1. Commit changes to `analysis/transform.Rmd`
1. Build  `analysis/transform.Rmd`
1. Commit `docs/transform.html` and `output/transformed.csv`

The above assumes that the data files are small enough to be version controlled (this is the ideal use case for workflowr). If not, the YAML headers would need to specify the R Markdown files. In other words, files that are listed in the YAML header are ones that you want to be version controlled.

Also note that the files paths are always relative to the root directory of the workflowr project. Since users can change the knit directory (where the code in the Rmd files is executed), using this convention ensures that this will work for everyone's project. Thoughts?

**Comment by jdblischak** [comment] 2019-05-08 15:09
>  If I run wflow_build(c("analysis1.Rmd", "analysis2.Rmd")), do the files always get build in the order in which they are listed?

@pcarbo Yes. But listing each file will always rebuild each file (regardless of whether or not it has been modified), so that doesn't function as a pipeline.

> If so, we should make that clear in the description of the file argument.

Done in 977bea95cda20e74d63001561118897e3fa23426

**Comment by antass** [comment] 2019-05-09 15:44
@jdblischak awesome. I'll get back to you with some ideas on how to handle ordering dependencies in YAML a little later.

For now, it looks like the numbering doesn't affect the order of the build after all:

```
> wflow_build(republish = TRUE)
Current working directory: /my/path/to/project
Building 7 file(s):
Building analysis/03_model.Rmd
  - Note: This file has a cache directory
Building analysis/04_visualize.Rmd
Building analysis/01_tidy.Rmd
Building analysis/02_transform.Rmd
Building analysis/about.Rmd
Building analysis/index.Rmd
Building analysis/license.Rmd
```

Any ideas?

**Comment by jdblischak** [comment] 2019-05-09 16:40
> I'll get back to you with some ideas on how to handle ordering dependencies in YAML a little later.

@antass Great! And another idea would be to specify the entire pipeline in `_workflowr.yml`. This would have the advantage that it would be easier to reason about and debug with everything in a central location.

**Comment by jdblischak** [comment] 2019-05-09 16:48
> For now, it looks like the numbering doesn't affect the order of the build after all:

@antass I'm having reproducing the behavior you observed. Could you please run the following and report your results? Note that this code will change your current working directory.

```
library(workflowr)
wflow_start(tempfile())
file.create(file.path("analysis", c("01_tidy.Rmd", "02_transform.Rmd",
                                    "03_model.Rmd", "04_visualize.Rmd")))
wflow_build(dry_run = TRUE)
wflow_publish("analysis/*Rmd")
wflow_build(republish = TRUE)
```

Here is what I get when I run it:

<details>
<summary>
Click to expand output:
</summary>
<pre>
> cwd <- getwd()
> on.exit(setwd(cwd))
> library(workflowr)
This is workflowr version 1.3.0.9000
Run ?workflowr for help getting started
> wflow_start(tempfile())
wflow_start:
- New directory created at /tmp/RtmpGq5SQe/file3e517b30de60
- Project name is "file3e517b30de60"
- Working directory changed to /tmp/RtmpGq5SQe/file3e517b30de60
- Git repo initiated at /tmp/RtmpGq5SQe/file3e517b30de60
- Files were committed in version e5bbb67
> file.create(file.path("analysis", c("01_tidy.Rmd", "02_transform.Rmd",
+                                     "03_model.Rmd", "04_visualize.Rmd")))
[1] TRUE TRUE TRUE TRUE
> wflow_build(dry_run = TRUE)
Summary from wflow_build

Settings:
 make: TRUE

The following would be built externally each in their own fresh R session: 

docs/01_tidy.html
docs/02_transform.html
docs/03_model.html
docs/04_visualize.html
docs/about.html
docs/index.html
docs/license.html
> wflow_publish("analysis/*Rmd")
Current working directory: /tmp/RtmpGq5SQe/file3e517b30de60
Building 7 file(s):
Building analysis/01_tidy.Rmd
Building analysis/02_transform.Rmd
Building analysis/03_model.Rmd
Building analysis/04_visualize.Rmd
Building analysis/about.Rmd
Building analysis/index.Rmd
Building analysis/license.Rmd
Summary from wflow_publish

**Step 1: Commit analysis files**

Summary from wflow_git_commit

The following was run: 

  $ git add analysis/01_tidy.Rmd analysis/02_transform.Rmd analysis/03_model.Rmd analysis/04_visualize.Rmd analysis/about.Rmd analysis/index.Rmd analysis/license.Rmd 
  $ git commit -m "wflow_publish(\"analysis/*Rmd\")" 

The following file(s) were included in commit b776b3c:
analysis/01_tidy.Rmd
analysis/02_transform.Rmd
analysis/03_model.Rmd
analysis/04_visualize.Rmd

**Step 2: Build HTML files**

Summary from wflow_build

Settings:
 clean_fig_files: TRUE

The following were built externally each in their own fresh R session: 

docs/01_tidy.html
docs/02_transform.html
docs/03_model.html
docs/04_visualize.html
docs/about.html
docs/index.html
docs/license.html

Log files saved in /tmp/RtmpGq5SQe/workflowr

**Step 3: Commit HTML files**

Summary from wflow_git_commit

The following was run: 

  $ git add docs/01_tidy.html docs/02_transform.html docs/03_model.html docs/04_visualize.html docs/about.html docs/index.html docs/license.html docs/figure/01_tidy.Rmd docs/figure/02_transform.Rmd docs/figure/03_model.Rmd docs/figure/04_visualize.Rmd docs/figure/about.Rmd docs/figure/index.Rmd docs/figure/license.Rmd docs/site_libs docs/.nojekyll 
  $ git commit -m "Build site." 

The following file(s) were included in commit b06ed34:
docs/01_tidy.html
docs/02_transform.html
docs/03_model.html
docs/04_visualize.html
docs/about.html
docs/index.html
docs/license.html
docs/site_libs/bootstrap-3.3.5/
docs/site_libs/highlightjs-9.12.0/
docs/site_libs/jquery-1.11.3/
docs/site_libs/jqueryui-1.11.4/
docs/site_libs/navigation-1.1/
docs/site_libs/tocify-1.9.1/
> wflow_build(republish = TRUE)
Current working directory: /tmp/RtmpGq5SQe/file3e517b30de60
Building 7 file(s):
Building analysis/01_tidy.Rmd
Building analysis/02_transform.Rmd
Building analysis/03_model.Rmd
Building analysis/04_visualize.Rmd
Building analysis/about.Rmd
Building analysis/index.Rmd
Building analysis/license.Rmd
Summary from wflow_build

Settings:
 make: TRUE republish: TRUE

The following were built externally each in their own fresh R session: 

docs/01_tidy.html
docs/02_transform.html
docs/03_model.html
docs/04_visualize.html
docs/about.html
docs/index.html
docs/license.html

Log files saved in /tmp/RtmpGq5SQe/workflowr
</pre>
</details>

**Comment by antass** [comment] 2019-05-09 18:06
@jdblischak these commands produced the expected output. 

And actually, most of the time the pages get built in the right order. I ended up running the same command again (`wflow_build(republish=TRUE)`) and the order was correct. 

I wonder if the order might be dependent on the status of the git snapshot for a file. If there are uncommitted changes in some files, these get built first (in order, so 03 -> 04), and then because of the `republish = TRUE`, the rest of the files get rebuilt (also in order, so 01 -> 02 -> about > etc).

If I recall correctly, 03 and 04 were the only files I was working on at that time..

**Comment by jdblischak** [comment] 2019-05-09 18:12
> I wonder if the order might be dependent on the status of the git snapshot for a file.

This was my suspicion as well. You can run `wflow_status()` to confirm the current status of each R Markdown file.

**Comment by antass** [comment] 2019-05-09 18:32
Ah, `wflow_status()` is very helpful! I'm actually thinking this behavior doesn't break anything - if there are no changes to the Rmd file, then no new data was generated, so it doesn't matter that the Rmd gets built after its "child".

**Comment by jdblischak** [comment] 2020-03-02 15:41
I'm closing this to keep the discussion in one place: Issue #9

**Closed as completed by jdblischak** 2020-03-02 15:41 UTC
