### ISSUE TITLE
Cached figures missing

### ISSUE THREAD

**Issue by lazappi** [workflowr/workflowr#113] opened 2018-07-31 06:09 UTC
Before reporting your bug, please search the existing issues (both "open" and "closed") to check that a similar bug has not already been reported.

1. Give the exact command or line of code you ran that caused the issue, e.g., `wflow_publish("myanalysis.Rmd")`.

`wflow_publish("myanalysis.Rmd")` or `wflow_build("myanalysis.Rmd")`.

2. Describe the result of running the command or code, including any warning or error messages.

Figures from cached chunks can be missing from produced reports. This is because `wflow_build` and `wflow_publish` delete the relevant `docs/figure` directory before knitting the document. If a cached chunk that produces a figure has already been run that figure won't be produced again but the previous version has already been deleted.

A simple solution would be to copy the figure directory from `analysis` to `docs` instead of moving it. That would mean having two copies of the files but only one needs to be in git. A bigger problem might be stale figures (e.g. figures from chunks that no longer exist) hanging around in the repository but they wouldn't be seen in reports so maybe not that important. Moving just the files in the figure directory rather than deleting the old directory and replacing it with a new one would have a similar effect without requiring two copies.

Is this something you want to be possible and are you likely to have time to look at it soon? In the meantime pressing the knit button doesn't have this problem (as far as I can tell) so doing that and manually committing is a reasonable workaround for now. This is related to #7 but I thought it was specific enough for new issue.

3. Tell us about your computing environment, including the version of R, RStudio and workflowr you are using. The simplest way to do this is to run `sessionInfo()` in R (and `RStudio.Version()` if you are using RStudio) and copy the output here.

**Comment by pcarbo** [comment] 2018-07-31 14:58
@lazappi Thanks for reporting this. Would you be able to share with us a very simple `.Rmd` file that reproduces this bug?

**Comment by lazappi** [comment] 2018-07-31 23:47
@pcarbo Pretty sure just adding this chunk to the default `index.Rmd` file is enough to replicate the problem but I can make a full example if you need.

`````
```{cache = TRUE}
plot(pressure)
```
`````

The plot will be there the first time it is run but if you run it again without changing that chunk it will be missing.

**Comment by jdblischak** [comment] 2018-08-01 00:27
Sorry for the delay. I know what the issue is.

The quick fix is to not cache your figures, but instead to separate the long-running chunks from the ones that generate the figures. To be explicit:


`````
```{r long-running, cache=TRUE}
x <- super_long_fun()
```
```{r plot}
plot(x)
```
`````

The longer term solution is tougher. I support temporarily caching chunks while iteratively developing an analysis (i.e. while using `wflow_build()`), but cached chunks shouldn't be used when finalizing an analysis with `wflow_publish()` since this violates the key assumption of workflowr: that the results you see were generated by that exact code across the entire file. I'm not sure at the moment how easy it will be to support both modes. Maybe it could be solved by documentation and a warning message?

**Comment by pcarbo** [comment] 2018-08-01 02:25
> Maybe it could be solved by documentation and a warning message?

@jdblischak Yes!

**Comment by lazappi** [comment] 2018-08-01 02:33
I guess I don't want to have to worry about turning caching on/off for particular chunks? I usually just turn it on globally.

Warnings/documentation would be good but the workflowr functions would still be incompatible with caching (but maybe you are ok with that?).

I've been thinking about it a bit and I think if it is done properly caching shouldn't make things less reproducible. If code in a chunk is changed then the cache should be invalidated and that chunk (and any that depend on it) should be rerun automatically. The `auto.dep` option in knitr makes that fairly straightforward, although it isn't foolproof. 

I guess I am willing to trade increased speed while I am developing an analysis for potential inconsistencies, then I just delete the cache and rerun everything when I want to sure it's consistent. I guess the compromise would be to allow caching for `wflow_build` but not for `wflow_publish`?

**Comment by jdblischak** [comment] 2018-08-01 14:18
> I guess I don't want to have to worry about turning caching on/off for particular chunks? I usually just turn it on globally.


> Warnings/documentation would be good but the workflowr functions would still be incompatible with caching (but maybe you are ok with that?).

I want to discourage the use of cached chunks to produce final results, but I also want to be pragmatic. Caching is useful when developing an analysis. Ideally workflowr would act as a safety net (i.e. if you forgot to disabling caching or manually delete the cache folder).

> I've been thinking about it a bit and I think if it is done properly caching shouldn't make things less reproducible. If code in a chunk is changed then the cache should be invalidated and that chunk (and any that depend on it) should be rerun automatically. The auto.dep option in knitr makes that fairly straightforward, although it isn't foolproof.

One problem is that the default for autodep is FALSE. I guess one thing workflowr could do is to always set autodep to TRUE.

> I guess I am willing to trade increased speed while I am developing an analysis for potential inconsistencies, then I just delete the cache and rerun everything when I want to sure it's consistent. I guess the compromise would be to allow caching for wflow_build but not for wflow_publish?

Yes, I think that sounds like a good compromise. The current issue is that the figure files are deleted by `wflow_build` (because `wflow_publish` calls `wflow_build`). This is done [here](https://github.com/jdblischak/workflowr/blob/a69257e13bf0238e0c61594d786230c97cdbcd24/R/wflow_build.R#L250). I could expose this as an argument to `wflow_build` (maybe `clean_figs`?). Then the default for `wflow_build` would be `clean_figs = FALSE`, but then `wflow_publish` would always call `wflow_build` with `clean_figs = TRUE`. Thoughts?

**Comment by pcarbo** [comment] 2018-08-01 14:39
> Then the default for wflow_build would be `clean_figs = FALSE`, but then `wflow_publish`s would always call `wflow_build` with `clean_figs = TRUE`. Thoughts?

@jdblischak Sounds great. But maybe call the argument `clean_fig_files` to make it more clear?

**Comment by lazappi** [comment] 2018-08-01 22:59
It might be better to have an `allow_caching` (or similar) that overrides the user caching settings or deletes the existing cache. If `wflow_publish` deletes the figure files but a useable cache still exists there will still be the same problem of figures not being produced. Basically I'm not sure that a `clean_figs` option would be sufficient to fix the problem.

Also out of curiosity @jdblischak what do you mean by "I want to discourage the use of chunks to produce final results"? What do you suggest/use instead? Or did you mean cached chunks?

**Comment by jdblischak** [comment] 2018-08-02 14:29
> It might be better to have an allow_caching (or similar) that overrides the user caching settings or deletes the existing cache. If wflow_publish deletes the figure files but a useable cache still exists there will still be the same problem of figures not being produced. Basically I'm not sure that a clean_figs option would be sufficient to fix the problem.

Good point, @lazappi! Perhaps this is the right time to enable workflowr to directly address caching.

> Also out of curiosity @jdblischak what do you mean by "I want to discourage the use of chunks to produce final results"? What do you suggest/use instead? Or did you mean cached chunks?

Yeah, sorry for the confusion. I meant "cached chunks". I've edited it above.

**Comment by pcarbo** [comment] 2018-08-02 17:43
> It might be better to have an allow_caching (or similar) that overrides the user caching settings or deletes the existing cache.

Agreed.

**Comment by FedericoComoglio** [comment] 2019-02-07 13:15
Hi, I'm currently using the suggested workaround, setting `cache = FALSE` for figure chunks. Is there any update on this issue that would allow full compatibility with caching?

Thank you.

**Comment by jdblischak** [comment] 2019-02-07 14:35
@FedericoComoglio No, but I have have recently added some new features related to caching for a soon-to-be-released version. Let me implement a `clean_fig_files` argument, and then it'd be great if you could test it and the other features out.

**Comment by FedericoComoglio** [comment] 2019-02-07 15:09
Great, sounds good. I look forward to testing them. 
Thank you.

**Comment by jdblischak** [comment] 2019-02-07 15:20
@FedericoComoglio @lazappi I've implemented the argument `clean_fig_files` in fc88fc5. It's currently on the "dev" branch. I'd appreciate it if you could try it out.

```
devtools::install_github("jdblischak/workflowr@dev")
```

I've also added a check for cached chunks to the reproducibility report, so please take a look at that as well.

**Comment by FedericoComoglio** [comment] 2019-02-07 17:11
Thank you. I will test it and let you know.

**Comment by jdblischak** [comment] 2019-02-07 17:18
@FedericoComoglio Thanks! And you may want to install from GitHub again. I just pushed a new argument `delete_cache` in 2dd3871 which you might find convenient for testing the caching features.

**Comment by lazappi** [comment] 2019-02-07 22:22
That looks like a reasonable solution. I'm in the middle of trying to finish the last bit of analysis for my thesis so I don't think I'll have time to test it but if it looks like there aren't any issues I would be keen to start using it.

**Comment by lazappi** [comment] 2019-02-07 22:25
Sorry, something I just noticed. Does there need to be some kind of warning about deleting the cache if `clean_fig_files` is `TRUE`, particularly in `wflow_publish`? If the figure files are deleted but the cache still exists we will be back where we started.

**Comment by jdblischak** [comment] 2019-02-08 14:51
>  I'm in the middle of trying to finish the last bit of analysis for my thesis

@lazappi Congrats! You're almost there!

> Does there need to be some kind of warning about deleting the cache if `clean_fig_files` is `TRUE`, particularly in `wflow_publish`? If the figure files are deleted but the cache still exists we will be back where we started.

It's difficult for workflowr to anticipate exactly what will happen. The arguments `clean_fig_files` and `delete_cache` are assessed and acted upon prior to building the Rmd file. Thus it doesn't know which of the existing cached chunks will be invalidated and re-executed. For now, I've added a message to `wflow_build()`/`wflow_publish()` that will alert the user if a cache directory is detected (190c564).

```
> wflow_build("analysis/cache.Rmd")
Current working directory: /home/jdb-work/Desktop/test-dev
Building 1 file(s):
Building analysis/cache.Rmd
  - Note: This file has a cache directory
Summary from wflow_build

Settings:


The following were built externally each in their own fresh R session: 

docs/cache.html

Log files saved in /tmp/RtmpiPzWu7/workflowr
> wflow_build("analysis/cache.Rmd", delete_cache = TRUE)
Current working directory: /home/jdb-work/Desktop/test-dev
Building 1 file(s):
Building analysis/cache.Rmd
  - Note: Deleted the cache directory before building
Summary from wflow_build

Settings:
 delete_cache: TRUE

The following were built externally each in their own fresh R session: 

docs/cache.html

Log files saved in /tmp/RtmpiPzWu7/workflowr
```

I'm open to making this more sophisticated in the future. Let's see how `clean_fig_files` and `delete_cache` are used in the wild first.

**Closed as completed** 2019-02-14 15:00 UTC

**Comment by jdblischak** [comment] 2019-02-14 17:49
@lazappi @FedericoComoglio The arguments `clean_fig_files` and `delete_cache` are now available in [workflowr 1.2.0](https://github.com/jdblischak/workflowr/releases/tag/v1.2.0). You can install it from the GitHub master branch or wait for it to be built and synced across the CRAN mirrors.

**Comment by FedericoComoglio** [comment] 2019-02-14 21:36
@jdblischak Awesome, thanks a lot. I tested these new arguments over the week and everything works as expected in my hands.

**Comment by jdblischak** [comment] 2019-02-15 15:12
Great. Thanks @FedericoComoglio!

**Comment by jma1991** [comment] 2021-02-03 14:41
Apologies for re-opening this issue, but I am encountering the same problem with the latest version of workflowr (1.6.2). I have multiple Rmd documents and each chunk has been cached. However, regardless if I run wflow_build or wflow_publish I cannot get either the analysis/figure or docs/figure files to be generated. Before I delete all of my cached work, is there a way I can generate the figures again? Thank you.

**Comment by jdblischak** [comment] 2021-02-03 18:39
> However, regardless if I run wflow_build or wflow_publish I cannot get either the analysis/figure or docs/figure files to be generated. Before I delete all of my cached work, is there a way I can generate the figures again?

@jma1991 If the figures don't exist in `docs/figure/` and the code chunks that produce the plots are cached, then unfortunately there is no way to regenerate the figures without re-running the code.

Here's how you can avoid this situation in the future:

1. Separate the computationally intensive code and the plotting code into separate code chunks. Set the plotting code chunks to never be cached with `cache = FALSE` (or the opposite strategy, only set `cache = TRUE` for the long-running code chunks)

1. For interactive analysis, you'll want to use `wflow_build()` exclusively. It never deletes any figure files.

1. When you are ready to publish your latest results, then use `wflow_publish()`. It deletes old figure files because these can easily add up as you interactively build your analysis (e.g. if you change the chunk name, or if you change the number of unnamed chunks). Even better would be to run `wflow_publish()` with `delete_cache = TRUE`. This will ensure that the latest results are truly generated by the latest code.

In general, the workflowr framework encourages caching to only be used during interactive development. The versioning it applies to each new set of results (i.e. every time you run `wflow_publish()`) makes the most sense when the results are re-generated each time. The same logic applies to the `sessionInfo()` appended to the end of the analysis. Even if the code in your Rmd file hasn't changed, the versions of the R packages installed on your machine might have changed. These updated package versions might break your analysis, and you'd never know if the results were generated from cached chunks.

Sorry for the inconvenience. Please let me know if you have any questions about my advice above, and thanks for using workflowr.

**Comment by FedericoComoglio** [comment] 2021-02-03 20:31
@jma1991 I agree with @jdblischak and points 1-3 are also the procedure I usually follow when working with computationally demanding code chunks. Additionally, it is easy to let Rmd files become unnecessarily bulky. Saving processed data/objects to the `output/` directory and modularizing your notebooks can prove quite effective to mitigate this issue.
