### ISSUE TITLE
fig.path not working for Python chunks

### ISSUE THREAD

**Issue by lazappi** [workflowr/workflowr#181] opened 2019-11-25 15:19 UTC
I've been trying to get workflowr working with a Python analysis and I'm running into an issue with chunks that create figures. The `fig.path` doesn't seem to be working properly and Python figures end up in `figure/DOCNAME/` instead of `docs/figure/DOCNAME` (and therefore don't show up on the website).  Not sure if it a problem with where they are created or they aren't being moved to the correct directory?

This test document should reproduce the issue, assuming you don't have any reticulate issues (need to rename to .Rmd).

[TEST.txt](https://github.com/jdblischak/workflowr/files/3887255/TEST.txt)

Potentially this is a niche problem but thought I would raise it and see if there is an easy fix.

**Comment by lazappi** [comment] 2019-11-25 15:34
FYI my hacky workaround for the moment is stick the following chunk at the end of the document. Seems to work but would be good to not have to do it.

```r
fs::file_move(
  fs::dir_ls(here("figure", DOCNAME)),
  here("docs", "figure", DOCNAME)
)
```

**Comment by jdblischak** [comment] 2019-11-25 16:06
@lazappi Thanks for bringing this to our attention and providing a nice minimal example for testing. I'll look into how workflowr can provide better support Python plots.

**Comment by jdblischak** [comment] 2019-12-03 20:08
> The fig.path doesn't seem to be working properly and Python figures end up in figure/DOCNAME/ instead of docs/figure/DOCNAME (and therefore don't show up on the website).

I was able to confirm this behavior.

> FYI my hacky workaround for the moment is stick the following chunk at the end of the document.

I was able to confirm your workaround, though I added some code to ensure that `docs/figure/DOCNAME` exists:

````
```{r move-python-figs, include=FALSE}
local({
  dir_fig <- here::here("docs", "figure", "python.Rmd")
  fs::dir_create(dir_fig)
  fs::file_move(
    fs::dir_ls(here::here("figure", "python.Rmd")),
    dir_fig
  )
})
```
````

Another quick fix would be to change the knit directory to `analysis/` by setting `knit_root_dir: "analysis/"` in `_workflowr.yml` (or alternatively deleting `knit_root_dir`).

The problem is that the Python plot is being saved to a different directory than the R plot. To see where they end up, you can add a code chunk with `stop()` to the end of the R Markdown file. For my file that I named `python.Rmd`, the R plot is saved to `analysis/figure/python.Rmd/unnamed-chunk-2-1.png`, and the Python plot is saved to `figure/python.Rmd/unnamed-chunk-3-1.png`.

This is why changing `knit_root_dir` works. When the R Markdown chunks are executed in the same directory as the file itself, both the R plot and Python plot are saved to `analysis/figure/python.Rmd/`, and this is the directory that `wflow_site()` moves to `docs/`.

I'll look into whether it is possible to get the Python chunks to behave the same as the R chunks in regards to the working directory.

**Comment by jdblischak** [comment] 2019-12-03 21:51
I also opened an Issue on the knitr repo to see if this can be fixed upstream: https://github.com/yihui/knitr/issues/1783

If not, I'll implement a workaround so that you don't have to manually add that hack to every file that uses Python plotting.

**Comment by lazappi** [comment] 2019-12-04 08:27
Thanks! Glad it is reproducible and I wasn't missing something obvious 😸. I hadn't thought about changing the knit directory, that might be a better option than the moving chunk.

Just out of curiosity what is the thinking behind using `local()` in your version of the chunk?

**Comment by jdblischak** [comment] 2019-12-04 19:02
> Just out of curiosity what is the thinking behind using local() in your version of the chunk?

It's not required, and was probably over-cautious.

My motivation to include it was part social and part technical. On the social side, anyone reading that chunk will know that it is a housekeeping detail and not part of the analysis. On the technical side, if anyone were to add a chunk below that one (or if workflowr in the future added more than just a session information chunk to the bottom of the docuement), the variable `dir_fig` wouldn't be able to interfere with it.

**Comment by lazappi** [comment] 2019-12-18 13:49
I think this has been partly fixed in the latest release of `reticulate` (v1.14). See https://github.com/rstudio/reticulate/issues/645 and https://github.com/rstudio/rmarkdown/issues/1686.

Unfortunately there seems to be another issue with absolute paths in `workflowr` projects 😿. I have opened an issue about that here https://github.com/rstudio/reticulate/issues/669 but it might be helpful if you can give some input.

**Comment by jdblischak** [comment] 2020-01-03 20:21
@lazappi Now that Issues https://github.com/rstudio/reticulate/issues/645 and https://github.com/rstudio/reticulate/issues/669 have been fixed in the dev version of reticulate, I have added a new feature to workflowr to insert a warning if the version of reticulate is outdated. I'll merge it into master once reticulate 1.15 is released.

Here's a screenshot of what it will look like if a user tries to include a Python plot using an outdated version of reticulate (I installed 1.13 to create this example):

![image](https://user-images.githubusercontent.com/1608317/71747074-b3f03200-2e3c-11ea-8aa7-316d879567b0.png)

Thanks again for all your help troubleshooting this issue!

**Comment by lazappi** [comment] 2020-01-04 09:45
No worries! I just found the issue, other people actually fixed it. 😸

That seems like a good solution to me. Should make it clear to people that it's a known issue and there is an easy fix (once reticulate 1.15 is available)

**Comment by jdblischak** [comment] 2020-02-28 20:12
Just checked. reticulate 1.15 still hasn't been released to CRAN.

**Comment by jdblischak** [comment] 2020-04-04 17:12
reticulate 1.15 was released to CRAN a few days ago (2020-04-02). I rebased and cleaned up my previous commit. I need to setup a CI job with Python to test this. Once that passes, I'll merge to master.

**Closed as completed** 2020-04-04 17:43 UTC
Labels: enhancement

**Comment by jdblischak** [comment] 2020-05-01 00:25
@lazappi The workflowr feature to warn about incompatible versions of reticulate is now on CRAN (version 1.6.2).
