### ISSUE TITLE
Images do not display when hosting on Shiny Server

### ISSUE THREAD

**Issue by Tutuchan** [workflowr/workflowr#119] opened 2018-08-27 10:41 UTC
Hello and thanks for this great package!

I noticed that images do not display when hosting the `docs` folder on a Shiny Server. I do not currently have a publicly available Shiny Server to showcase this but I may try to spin one if you'd like.

The issue stems from the figure directory, which is `basename(<analysis_file>)`. This creates a `figure/xxx.Rmd` directory and Shiny Server interprets paths ending in `.Rmd` in a specific manner which clashes with static files hosting. I'd recommend removing the file extension for the figure directory (starting from [here](https://github.com/jdblischak/workflowr/blob/2fc23293e38d0b3fd96a208d2a023ac712fe0247/R/wflow_html.R#L159)). 

I'd be happy to submit a PR.

Thanks,
Pierre

**Comment by pcarbo** [comment] 2018-08-27 11:53
@jdblischak Have you tested workflowr with shiny? It would be interesting to have a small example illustrating the use of workflowr & shiny?

**Comment by jdblischak** [comment] 2018-08-27 12:56
> Hello and thanks for this great package!

Thanks Pierre! I appreciate you using and helping to improve workflowr!

> I noticed that images do not display when hosting the docs folder on a Shiny Server. I do not currently have a publicly available Shiny Server to showcase this but I may try to spin one if you'd like.

That is strange. Please do spin up a toy example to demonstrate the issue when you get the chance.

> The issue stems from the figure directory, which is basename(<analysis_file>). This creates a figure/xxx.Rmd directory and Shiny Server interprets paths ending in .Rmd in a specific manner which clashes with static files hosting. I'd recommend removing the file extension for the figure directory (starting from here).

I would prefer not to change the default figure path. This would negatively affect current workflowr projects. If the figure path changed, then the table of past figure versions that workflowr inserts into the document would be truncated (due to the filename name change).

> I'd be happy to submit a PR.

Here are the options I'd like to explore first:

1. Is it possible to fix this on the Shiny Server side. It should be smart enough to realize a directory with the name `file.Rmd/` is not an R Markdown file.
2. Expose the `fig.path` as a configurable option for workflowr projects. Then we could add documentation that this needs to be changed if hosting a workflowr project with Shiny Server.

@Tutuchan Thoughts?

**Comment by jdblischak** [comment] 2018-08-27 13:01
> Have you tested workflowr with shiny? It would be interesting to have a small example illustrating the use of workflowr & shiny?

@pcarbo I haven't, but I think this would be a good opportunity to get contributions from the workflowr community. It would be more useful for other users to see real use cases (e.g #115) instead of any contrived example I come up with. Let's figure out this issue with the `fig.path` and then think about how best to showcase Shiny+workflowr.

**Comment by Tutuchan** [comment] 2018-08-27 14:13
Thanks for the quick response.

I'll try to spin a server this afternoon and report back.

As for the two options:
1. I'm not sure it can be handled in Shiny Server for now, I am pretty sure it does not discriminate between files and directories when serving a directory (I think it's [here](https://github.com/rstudio/shiny-server/blob/4b588a12f844713729991d1274764d854d90a18d/lib/router/router.js#L236-L244)).
2. This could be a good compromise for the time being.

**Comment by Tutuchan** [comment] 2018-08-27 14:34
Ok @jdblischak, if you can connect to http://b691861d.ngrok.io, you should see two folders hosted on a local Shiny server on my machine:

+ `workflowr` is the current behaviour, with figures in figure/index.Rmd/...
+ for `workflowr-no-rmd`, I just changed the path manually to figure/index/... and the link in the `index.html` file

As you can see, the first case is not working but the second is.

**Comment by jdblischak** [comment] 2018-08-31 15:28
> As you can see, the first case is not working but the second is.

@Tutuchan Thank you very much for the examples (I tested them a few days ago when they were still live).

I also confirmed the behavior locally using the Docker image [rocker/shiny](https://hub.docker.com/r/rocker/shiny/). My notes for my future self below:

1. Create a workflowr project and publish an analysis that creates a plot
1. Start a Docker container running Shiny Server to serve the workflowr project
    ```
     docker run -d --rm -p 3838:3838 --name dshiny \
        -v ~/Desktop/wflow-shiny/docs:/srv/shiny-server/ rocker/shiny
    ```
1. Open Shiny Server in the browser:
    ```
     firefox http://localhost:3838
    ```
1. Edit the name of the figure directory and the `img` filepaths.
    a. This can be done in the local filesystem
    b. Or inside the running Docker container
        ```
        docker exec -it dshiny bash
        ```
1. Stop the container
    ```
     docker stop dshiny
    ```

**Comment by jdblischak** [comment] 2018-08-31 15:59
I put together a [minimal example](https://rstudio.cloud/project/60968) on RStudio Cloud and opened Issue https://github.com/rstudio/shiny-server/issues/377.

**Comment by Tutuchan** [comment] 2018-09-03 07:36
Thanks @jdblischak !

Do you want me to work on option 2 in the meantime ?

**Comment by jdblischak** [comment] 2018-09-04 01:09
> Do you want me to work on option 2 in the meantime ?

@Tutuchan That'd be great if you could work on this! Before you start writing any code, let's brainstorm how best to accomplish this.

1. One option would be to add an optional field, e.g. `wflow_fig_path`, to `_workflowr.yml` that would allow the user to specify the directory to save the figures. Then the figure hook [hook_fig_path()](https://github.com/jdblischak/workflowr/blob/dev/R/wflow_html.R#L158) could call the function [wflow_options()](https://github.com/jdblischak/workflowr/blob/dev/R/wflow_options.R#L10). And `wflow_options()` would set the default to `file.path("figure", knitr::current_input())`. I like the ultimate flexibility of this strategy, but I worry it is too complicated and dangerous. First, the solution would be changing the figure path to something like `file.path("figure", tools::file_path_sans_ext(knitr::current_input()))`, which is difficult to read and type, especially in a YAML file. Second, this has the potential to cause real problems if the user's chosen directory does not specify the Rmd source of the figure. For example, if the user sets the directory to be `figure/`, then figures originating from the same chunk name but different files will be erroneously overwritten.

1. A less flexible, but much simpler solution, would be to add a binary flag to `_workflowr.yml`, `fig_path_ext: FALSE`, indicating whether or not to include the `.Rmd` file extension in the figure path. Once again, `hook_fig_path()` could call `wflow_options()` to determine if the `.Rmd` file extension needs to be removed.

1. A third option would be to add a binary flag to `_workflowr.yml` that allows changing the figure path from the workflowr default to the rmarkdown default, i.e. `<filename-wo-ext>_files/figure-html`. This creates a lot of top-level subdirectories (which is one of the reasons why I changed it in the first place), but it is familiar to users (and will certainly work with any RStudio products).

And no matter which solution we choose, implementing this will require some refactoring. Multiple functions rely on figures being saved in the current location (`wflow_build()`, `wflow_publish()`, `wflow_site()`, `wflow_remove()`). Also, we'll need to reconcile it with some recent warnings I added to detect if the user tries to change `fig.path` within the Rmd file (see #114).

@Tutuchan Thoughts on these strategies? Is there one you prefer or do you have a different idea? I realize this was a lot of information. If you can implement a basic prototype and write some documentation for deploying with Shiny Server, I can handle refactoring the other functions to work with this new setup.

**Comment by Tutuchan** [comment] 2018-09-04 08:12
@jdblischak I actually forked the repo last week and kind of had the same thought process as you presented here on how to implement this change.

I made a quick implementation of your 2nd solution [here](https://github.com/Tutuchan/workflowr/commit/0cd98379f8017ed0959763f04330f802a450723e) because I needed a quick fix. 

I think this is the best solution of the three because I'm not sure the flexibility brought by option 1 is really needed in this context. And as you said, it may cause real problems, with little gains. I don't like the many top-level directories with the rmarkdown default either, it is neater to have a `figure` folder to store them.

I will take some time before the end of the week to clean up the code and add more documentation if that suits you.

**Comment by jdblischak** [comment] 2018-09-04 13:10
> I made a quick implementation of your 2nd solution here because I needed a quick fix.

@Tutuchan Wow! I'm impressed!

> I will take some time before the end of the week to clean up the code and add more documentation if that suits you.

That sounds good. Do you enjoy using Git? Ideally I'd like you to do the following to your commit:

1. Amend it to only edit the files in `R/` (and you can also keep the update to `.gitignore`). It looks like you didn't change any of the documentation, so there's no need to update the files in `man/` and `docs/` (most of those changes are due to differences in the roxygen2 version).
1. Rebase the commit onto the dev branch

But please don't let the above requests delay your contribution. I am happy to help with this after you submit a PR.

For the documentation, are you planning on putting together complete instructions for hosting with Shiny Server? I was thinking it might be a good idea to have a vignette with alternative hosting options (i.e. not Git hosting sites like GitHub and GitLab). We could include the Shiny Server instructions and also migrate the [Beaker Browser instructions](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#can-i-share-workflowr-websites-directly-with-collaborators-in-a-secure-fashion) from the FAQ to this vignette.

**Comment by Tutuchan** [comment] 2018-09-05 11:52
Alright, I'll amend the commit as requested.

As for the instructions, what do you mean by complete instructions ? There are already many tutorials on setting up a Shiny Server so I don't think it is necessary to recap it in `worfklowr`, maybe giving a few links is sufficient. I think giving pointers on how to send the files to the server (_via_ scp, for example), possibly automated with a `git` hook is a good place to start. What do you think about it ?

I like the idea of a new vignette with the Beaker browser + Shiny server hosting instructions.

**Comment by jdblischak** [comment] 2018-09-05 15:55
> Alright, I'll amend the commit as requested.

Great. And as I said above, please don't be burdened by this request. I realize you re-generated the docs because you followed my contributing instructions, so that's on me.

> As for the instructions, what do you mean by complete instructions ? There are already many tutorials on setting up a Shiny Server so I don't think it is necessary to recap it in worfklowr, maybe giving a few links is sufficient. I think giving pointers on how to send the files to the server (via scp, for example), possibly automated with a git hook is a good place to start. What do you think about it ?

Agreed. I'll leave this to your judgement. I think it will be fine to provide an overview, with links to external resources with more specific details on the non-workflowr-specific steps.

> I like the idea of a new vignette with the Beaker browser + Shiny server hosting instructions.

OK. Great. Maybe we should do this in two separate PRs. First submit the technical PR that implements the feature. Once we review and merge that PR, then I can create a new vignette for you to add the instructions. How does that plan sound?

**Comment by jdblischak** [comment] 2018-09-14 14:02
Fixed by @Tutuchan in PR #122.

@Tutuchan I created a new vignette for documenting alternative deployment strategies. Could you please add your instructions here for deploying with Shiny Server? As we discussed above, you can focus mostly on the workflowr-specific steps (e.g. setting `fig_path_ext`) and then provide links to more thorough instructions.

https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-08-deploy.Rmd

Also, would you like to be added as a contributor to the package? If yes, please let me know if the following entry looks good to you.

```
person("Pierre", "Formont", role = c("ctb"),
           comment = "Support for hosting with Shiny Server")
```

**Comment by Tutuchan** [comment] 2018-09-14 15:26
Thanks @jdblischak ! I'll get started on the documentation in the next few days.

Yes, the contributing entry looks good.

**Comment by jdblischak** [comment] 2019-02-18 20:36
Now live in workflowr 1.2.0. Thanks @Tutuchan!

**Closed as completed by jdblischak** 2019-02-18 20:36 UTC
