### ISSUE TITLE
commit rmd vs html

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#14] opened 2017-01-24 19:39 UTC
as I'm working i realize there is a point of potential confusion.
Currently `wflow_commit` commits an rmd file, then renders it, then commits html.
In some cases I might want to just commit the rmd file without rendering. (eg when it is not
yet ready)

one possibility of course would be to directly commit that via git on command line.
but it might be nice to be able to do this via wflow, eg by having a `render=FALSE` option
to wflow_commit

**Comment by jdblischak** [comment] 2017-01-24 22:17
Hmmm...we need to think about this. Some thoughts:

* `wflow_commit` now encapsulates two distinct functions. One is the more simple act of adding/committing specified files. This is simply provided as a convenience so that it can be quickly run in R instead of using Git at the command line (or the RStudio Git pane). The second is much more complex. It is searching the Git commit history to determine which files to re-build and commit, which is central to the workflowr paradigm and is much more difficult to perform manually. I think it would be dangerous to have an argument like `render = FALSE` determine whether the much more complex action is performed afterwards, as it would be difficult to undo. Perhaps they need to be split?

* Here's a proposal for splitting the functionality, but not adding too much to the complexity. We could enhance `wflow_build` to have an argument `commit = FALSE`. Thus the default action would be the current Makefile-like behavior of `wflow_build`. But if `commit = TRUE`, instead the commit history is searched and the original `wflow_commit` behavior is performed (i.e. re-build HTML, commit website files).

* We need to decide how to manage "draft" R Markdown files. Currently there is no mechanism for them to hide. `wflow_commit` searches the commit history for any file ending in `Rmd`. Even if you set `render = FALSE` when initially committing it, if you would make a subsequent call to `wflow_commit` with `render = TRUE`, it would attempt to build and commit the draft. One option would be to have drafts end in `rmd`. Thus they would be recognized by RStudio as R Markdown, they would be built for the website locally, but the HTML would never be committed and pushed to GitHub (relevant to the discussion in #10). A second option would be to recommend storing drafts in a subdirectory `drafts/` in the base of the project repository. Thus any relative paths would work when the file is moved to `analysis/`, but when rendered in drafts it would not have the website styling (which isn't that big of a deal, but more difficult for those new to Git would be moving the file from `drafts/` to `analysis/`. A third option would be to have a field in the YAML header that specifies what to do with the file. For example, `status: skip` would mean the file should be skipped by both `wflow_build` and `wflow_commit` (perhaps b/c the author knows it throws an error), `status: draft` would be built by `wflow_build` for previewing the site but skipped by `wflow_commit`, and `status: complete` (or absence of the field) would be built by both `wflow_build` and `wflow_commit`.

**Comment by stephens999** [comment] 2017-01-27 14:24
i agree this needs some thought. Let's not rush into anything here.

One thing I want to avoid is encouraging people to keep a whole bunch of
rmd files that they render locally but don't put on the website just because
they are "not quite ready".. .the danger is you never think anything is really quite ready
to go on a website. My goal is that the websites be treated like a notebook, so they
really are always a draft and never "final".  For this reason I'm not so keen on having
a drafts subdirectory... I could just see files never migrating out of there!

**Comment by stephens999** [comment] 2017-01-27 14:28
@jdblischak  can i check that `wflow_commit` with default arguments does not actually commit any new rmd files? 
So if I have a new `draft.rmd` file in `analysis` that is not part of my git history, and I run
`wflow_commit()` then it will not render `draft.rmd`? 
But if I run
`wflow_commit(commit_files="draft.rmd")`
then it will commit draft.rmd, adding it to my git repo, and thus rendering it in the second step?

What happens with `wflow_commit(all=TRUE)` ?

**Comment by jdblischak** [comment] 2017-01-27 15:14
> For this reason I'm not so keen on having a drafts subdirectory... I could just see files never migrating out of there!

I agree this is dangerous, and we want to encourage users commit both the Rmd and HTML of their analyses. But if this is how many users want to work, I'd like to provide them a better option than just letting the files languish in the working directory (i.e. never committing them to version control).

Yes, you understand correctly the first two options of `wflow_commit`. For the 3rd, `wflow_commit(all = TRUE)`, this builds all Rmd files that have been committed in the past and have no current changes in the working directory (or staging area). The idea is this would be used when changing the theme or some other aesthetic. You want to re-build all the pages and commit them, regardless of whether the content in the Rmd files have changed. In your hypothetical example, `draft.Rmd` would be ignored because it had not been committed yet.

Below is how I currently describe these 3 options in the Details section of the `wflow_commit` documentation ([source](https://github.com/jdblischak/workflowr/blob/bf10fcdd40dd674fca479a3421521f3cae360b0c/R/wflow_commit.R#L137)):

> First, running wflow_commit with the default arguments will identify all R Markdown files which have been modified more recently in the Git commit history than their corresponding HTML files. Furthermore these files must not currently have any subsequent changes that have not been committed. The files will be built and the correspoding HTML committed.
> 
> Second, you can have wflow_commit first add and commit files specified with the argument commit_files. A message for this commit can also be specified with the argument commit_message. After this commit has been made, wflow_commit then searches the Git commit history as described above.
> 
> Third, you can have wflow_commit re-build and commit all the webpages by setting all = TRUE. This is useful if you are making an aesthetic change, e.g. the theme, that needs to be applied regardless of whether the R Markdown file has been edited. Only tracked files without uncommitted changes will be re-built (this prevents the HTML not matching the corresponding R Markdown file).

**Comment by jdblischak** [comment] 2017-01-27 16:15
> For this reason I'm not so keen on having a drafts subdirectory... I could just see files never migrating out of there!

I agree this is dangerous, and we want to encourage users commit both the Rmd and HTML of their analyses. But if this is how many users want to work, I'd like to provide them a better option than just letting the files languish in the working directory (i.e. never committing them to version control).

Yes, you understand correctly the first two options of `wflow_commit`. For the 3rd, `wflow_commit(all = TRUE)`, this builds all Rmd files that have been committed in the past and have no current changes in the working directory (or staging area). The idea is this would be used when changing the theme or some other aesthetic. You want to re-build all the pages and commit them, regardless of whether the content in the Rmd files have changed. In your hypothetical example, `draft.Rmd` would be ignored because it had not been committed yet.

Below is how I currently describe these 3 options in the Details section of the `wflow_commit` documentation ([source](https://github.com/jdblischak/workflowr/blob/bf10fcdd40dd674fca479a3421521f3cae360b0c/R/wflow_commit.R#L137)):

> First, running wflow_commit with the default arguments will identify all R Markdown files which have been modified more recently in the Git commit history than their corresponding HTML files. Furthermore these files must not currently have any subsequent changes that have not been committed. The files will be built and the correspoding HTML committed.
> 
> Second, you can have wflow_commit first add and commit files specified with the argument commit_files. A message for this commit can also be specified with the argument commit_message. After this commit has been made, wflow_commit then searches the Git commit history as described above.
> 
> Third, you can have wflow_commit re-build and commit all the webpages by setting all = TRUE. This is useful if you are making an aesthetic change, e.g. the theme, that needs to be applied regardless of whether the R Markdown file has been edited. Only tracked files without uncommitted changes will be re-built (this prevents the HTML not matching the corresponding R Markdown file).

**Comment by pcarbo** [comment] 2017-01-27 23:45
Interesting discussion. I haven't completely followed every detail of this discussion, but I'll try my best to contribute to this discussion.

+ I completely agree that we want to discourage behaviour such as creating "draft" scripts, or files with names like "analysis_test8.Rmd". The whole point of git is that it shields the user from having to keep track of different drafts and revisions.

+ I also like the "feature" of workflowr in which rendering/knitting is coupled with commits. This has the double advantage of (1) recording an automatic history, (2) associating analysis versions with commit ids.

+ However, I completely agree that you should be able to test out revisions to your analysis without committing; it would be sort of like having to commit a text file every time you click "save", which is not desirable. In fact, one of the important features of git is being able to "stage" files for commit, which allow to control the granularity and scope of your revisions. For example, suppose I was working on analysis1.Rmd and analysis2.Rmd, and I was happy with my changes to analysis1.Rmd but not analysis2.Rmd, I would like to commit changes to analysis1.Rmd only. In other words, this finer-scale control of commits is one of the key features of git, and we don't want to lose it.

I have to run, but I'll think about this issue more and see if I can suggest a way forward here.

**Comment by stephens999** [comment] 2017-01-28 20:29
I propose the following changes:

1. That `wflow_commit("file.rmd")` should have the limited effect of
- git commit file.rmd
- render file.rmd
- commit the resulting html and figures 
so no searching all the other rmd files you might have updated and doing those.
[If a list or vector of filenames is provided then these would be processed in turn, in the order provided.]

2. That `wflow_commit(all=TRUE)`
has the effect of the current `wflow_commit()`.
That is it commits all rmd files that have been updated, then renders them and commits the html/docs.
[note that I am suggesting repurposing the use of the `all`  parameter here from its current use]

3. that the current "all" parameter be replaced with a "force" parameter.
If `force=TRUE` then `wflow_commit` does not check for changes in rmd files before re-rendering.
Note that `force` can be used with all or with a list of specific files.
So you could use `wflow_commit(all=TRUE,force=TRUE)` to completely rebuild whole website.
Or `wflow_commit("index.rmd", force=TRUE)` to rebuild the index even if the rmd hasn't changed
(eg to change the style of the index).

4. that wflow_commit() not do anything (ie user has to supply a file or set `all=TRUE`)

5. that `wflow_build` have the same semantics (although i never use it so haven't thought about this
very hard!)

Regarding merging `wflow_build` and `wflow_commit`, I personally
 like the different names for the different behaviour, rather than just setting a commit flag=TRUE in 
`wflow_build`.  So from a UI perspective I don't favor merging them into a single command but with a flag to  indicate which. [But you could always implement them that way if it helps... eg
have wflow_commit() be an alias for wflow_build(..., commit=TRUE).]
 
I think these suggestions would allow a lot of the functionality that I would want
for draft rmd files. If you were working on 5 files, but 3 of them were not yet ready, you would
just `wflow_commit("file1.rmd", "file2.rmd")` and the rest would be left alone.

I would envisage that `wflow_commit("file.rmd")` would be my everyday use,
and `wflow_commit(all=TRUE)` would be used only rarely.
And `wflow_commit(all=TRUE, dry_run=TRUE)` might be useful to see which rmd files
I've updated but not committed. (but this might be better put into a `wflow_status` command).

**Comment by pcarbo** [comment] 2017-01-28 21:41
This generally makes sense to me. (With some of the details of the interface to be worked out.)

I'd like to try to boil down the key elements of this discussion. Please let me know what is missing or incorrect from my description.

+ The process of revising a workflow website will mainly involve two actions: (1) committing ("versioning") revised files, (2) rendering notebooks into webpages.

+ To date, (1) and (2) have been wrapped up in a single function, `wflow_commit`.

+ It is sometimes useful to do (2) without doing (1); e.g., to test that the notebook produces the expected output.

+ However, one disadvantage of (2) without (1) is that a unique SHA-1 is not generated for this version of the rendered webpage. In other words, this guarantee (from the "getting started" vignette") is lost:

> By including the unique identifier that Git assigns a snapshot (or “commit” as Git calls it) 
> at the top of each of your HTML files, you always know which version of the code 
> produced the results.

As John says in `help(wflow_commit):

> In order for [the version] to be meaningful, the R Markdown file must not have changed 
> since it was last committed.

+ One way to resolve this issue is to write something the following underneath the "Last Updated" line in the webpage: `This page has not yet been committed, so no version/snapshot id has been assigned to this code.`

+ Have we discussed whether it is useful to do (1) without (2)? My thought is that we should prevent users from doing this; that is, *all commits must be accompanied by a rendering of all notebooks into webpages.* This implies that there is a 1-to-1 mapping between commits and website versions. This also means that you cannot commit until all webpages can be rendered succesfully.

**Comment by jdblischak** [comment] 2017-01-30 18:18
Great. Thanks for the feedback. @stephens999, I like your API suggestions. I had been focusing of solving the hard problem (how to ensure all HTML files are up-to-date), but it makes sense that standard usage will be to commit one (or at most a few) Rmd files at once. Thus the hard problem of searching the Git commit logs can be relegated to an optional argument.

However, I feel like this workflow doesn't address drafts. I'd rather have users commit a draft (or an experimental change to an already-tracked file) instead of keeping these only in the working directory. Left in the working directory, this work can be lost if accidentally deleted, and also cannot be worked on from multiple computers.

@pcarbo recommended a hard-line approach: all commits should also be rendered. While I agree in principal, I know I have made incremental changes to a large file that I want to commit, but am not ready to change the whole public file on the internet until I make additional changes. What about a compromise solution? The default action of `wflow_commit("file.Rmd")` will also build and commit the HTML to encourage a 1-to-1 mapping between Rmd and HTML. However, the user could have the option of running `wflow_commit("file.Rmd", build = FALSE)` (which they could technically do anyways with `git add file.Rmd` from the shell), which would come with a warning message that encourages them to commit the HTML as well as soon as possible. Thoughts?

**Comment by pcarbo** [comment] 2017-01-30 18:25
That sounds fine to me. The approach is to encourage "best practice", but to allow for flexibility.

Note that I believe this would allow for situations like this:

1. render webpage without commit (code version is invalid).

2. commit without rendering (published webpage now has invalid code version).

What do you think about my suggestion above to not assign a code version to webpage renderings that are not accompanied by a commit? I think that would help address this situation.

**Comment by pcarbo** [comment] 2017-01-30 19:26
One additional thought on this, followed by a somewhat radical idea:

+ I agree that committing without rendering should be discouraged (*i.e.*, not default), but available as an option for flexibility.

+ What if we create a new functionality that **does** provide a stronger reproducbility guarantee, and we call it a "release". This function could, for example, re-render all webpages, create a new release tag (and maybe even push the new tag to the remote?). This could be a new function `wflow_release`, or an additional option to `wflow_commit`. I guess this is like `wflow_commit(all = TRUE)`, but with the additional step of creating a tag (and underused feature of git).

In effect, the workflow has two loops: an inner loop in which the user experiments ("commits"); and outer loop in which the user finalizes the results for sharing ("releases").

**Comment by stephens999** [comment] 2017-01-30 20:01
@jdblischak regardign What about a compromise solution? The default action of wflow_commit("file.Rmd") will also build and commit the HTML to encourage a 1-to-1 mapping between Rmd and HTML. However, the user could have the option of running wflow_commit("file.Rmd", build = FALSE)

wasn't that my suggestion when i first opened this issue ? :) (I used `render =FALSE` but same idea)

**Comment by jdblischak** [comment] 2017-01-31 16:26
@pcarbo, to your first point on changing the commit ID based on the status of the HTML, in principle I like the idea. I could update `extract_commit` to run `git status`, and if the Rmd has changes in the working directory or staging area, then it would put "Not Available until Rmd has been committed" or something to that affect.

To your second point, I like the idea of a function that creates a tag after first running `wflow_commit(force = TRUE)` to make sure the HTML are up-to-date.

@stephens999, yes! It appears we've come full circle!

**Comment by jdblischak** [comment] 2017-06-19 20:31
Matthew's suggested interface has been implemented in `wflow_publish()` in [workflowr 0.5.0](https://github.com/jdblischak/workflowr/releases/tag/v0.5.0) (although the argument names are slightly different to avoid name conflicts with `git2r::commit()`). To summarize:

* `wflow_publish("file.Rmd")` only commits, builds, and commits the HTML for `file.Rmd`
* `wflow_publish(update = TRUE)` finds R Markdown files that have been committed more recently than their corresponding HTML files, builds them, and commits the HTML (this is the previous default behavior of `wflow_commit()`)
* `wflow_publish(republish = TRUE)` builds all previously published R Markdown files and commits the HTML (which is useful for site-wide modifications like changing the theme)

For any further refinements of `wflow_publish()` or the general workflow, we should open a new Issue to discuss.

**Closed as completed by jdblischak** 2017-06-19 20:31 UTC
Labels: enhancement
