### ISSUE TITLE
https://jdblischak.github.io/workflowr is not secure

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#96] opened 2018-01-30 17:33 UTC
According to Firefox. It is probably due to images or Javascript not being included with `https://`.

**Comment by jdblischak** [comment] 2018-01-30 17:58
Nice catch! I suspect this is caused by the badge for the CRAN status (to show that it is not yet published).

https://github.com/jdblischak/workflowr/blob/871e728c466bcc2ba12f8eab573ab42a873e209a/docs/index.html#L273

I added the CRAN badge with `usethis::use_cran_badge()`, which uses http for the image ([source](
https://github.com/r-lib/usethis/blob/53daf57ab0fab30b881287fb157847cec88ff1aa/R/badge.R#L12)).

**Comment by pcarbo** [comment] 2018-01-30 18:02
@jdblischak Great. Let me know when you want me to test this.

**Comment by jdblischak** [comment] 2018-01-31 02:37
<img width="350" alt="screen shot 2018-01-30 at 9 29 08 pm" src="https://user-images.githubusercontent.com/1608317/35602300-a3695e36-0605-11e8-8752-46b6ddbcf5a3.png">

This should be fixed now. Could you please confirm you get the same result in your browser?

**Comment by pcarbo** [comment] 2018-01-31 02:40
@jdblischak It is fixed in Firefox.

**Closed as completed** 2018-01-31 02:42 UTC
